/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CallerFunctionInfo
 */
public class CallerFunctionInfoTest {
    private final CallerFunctionInfo model = new CallerFunctionInfo();

    /**
     * Model tests for CallerFunctionInfo
     */
    @Test
    public void testCallerFunctionInfo() {
        // TODO: test CallerFunctionInfo
    }

    /**
     * Test the property 'functionId'
     */
    @Test
    public void functionIdTest() {
        // TODO: test functionId
    }

    /**
     * Test the property 'matchedFunctionId'
     */
    @Test
    public void matchedFunctionIdTest() {
        // TODO: test matchedFunctionId
    }

    /**
     * Test the property 'dashboardUrl'
     */
    @Test
    public void dashboardUrlTest() {
        // TODO: test dashboardUrl
    }

    /**
     * Test the property 'isExternal'
     */
    @Test
    public void isExternalTest() {
        // TODO: test isExternal
    }

    /**
     * Test the property 'callerName'
     */
    @Test
    public void callerNameTest() {
        // TODO: test callerName
    }

    /**
     * Test the property 'callerVaddr'
     */
    @Test
    public void callerVaddrTest() {
        // TODO: test callerVaddr
    }

}
