/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * The version of the OpenAPI document: v1.92.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import ai.reveng.model.FunctionInfoOutput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FunctionDataTypesListItem
 */
public class FunctionDataTypesListItemTest {
    private final FunctionDataTypesListItem model = new FunctionDataTypesListItem();

    /**
     * Model tests for FunctionDataTypesListItem
     */
    @Test
    public void testFunctionDataTypesListItem() {
        // TODO: test FunctionDataTypesListItem
    }

    /**
     * Test the property 'completed'
     */
    @Test
    public void completedTest() {
        // TODO: test completed
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'dataTypes'
     */
    @Test
    public void dataTypesTest() {
        // TODO: test dataTypes
    }

    /**
     * Test the property 'dataTypesVersion'
     */
    @Test
    public void dataTypesVersionTest() {
        // TODO: test dataTypesVersion
    }

    /**
     * Test the property 'functionId'
     */
    @Test
    public void functionIdTest() {
        // TODO: test functionId
    }

}
