/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * The version of the OpenAPI document: v1.92.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Process
 */
public class ProcessTest {
    private final Process model = new Process();

    /**
     * Model tests for Process
     */
    @Test
    public void testProcess() {
        // TODO: test Process
    }

    /**
     * Test the property 'pid'
     */
    @Test
    public void pidTest() {
        // TODO: test pid
    }

    /**
     * Test the property 'procname'
     */
    @Test
    public void procnameTest() {
        // TODO: test procname
    }

    /**
     * Test the property 'executableName'
     */
    @Test
    public void executableNameTest() {
        // TODO: test executableName
    }

    /**
     * Test the property 'args'
     */
    @Test
    public void argsTest() {
        // TODO: test args
    }

    /**
     * Test the property 'tsFrom'
     */
    @Test
    public void tsFromTest() {
        // TODO: test tsFrom
    }

    /**
     * Test the property 'tsTo'
     */
    @Test
    public void tsToTest() {
        // TODO: test tsTo
    }

    /**
     * Test the property 'children'
     */
    @Test
    public void childrenTest() {
        // TODO: test children
    }

}
