apiPackage: ai.reveng.api
modelPackage: ai.reveng.model
invokerPackage: ai.reveng.invoker
groupId: ai.reveng
artifactId: sdk
artifactUrl: https://github.com/RevEngAI/sdk-java
artifactDescription: Java SDK for the RevEng.AI API
licenseName: MIT
licenseUrl: https://opensource.org/license/mit
developerName: RevEng.AI
developerEmail: support@reveng.ai
developerOrganization: RevEng.AI
developerOrganizationUrl: https://reveng.ai
scmConnection: scm:git:git@github.com:RevEngAI/sdk-java.git
scmDeveloperConnection: scm:git:git@github.com:RevEngAI/sdk-java.git
scmUrl: https://github.com/RevEngAI/sdk-java
library: okhttp-gson
# Do not include timestamps in the generated files to avoid unnecessary diffs
hideGenerationTimestamp: true
# Allow unknown properties to avoid breaking when the API adds new fields, and we haven't updated the SDK yet
disallowAdditionalPropertiesIfNotPresent: false
typeMappings:
  integer+bigint: java.math.BigInteger
importMappings:
  BigInteger: java.math.BigInteger