/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.api;

import ai.reveng.invoker.ApiException;
import ai.reveng.model.AnalysisCreateRequest;
import ai.reveng.model.AnalysisUpdateRequest;
import ai.reveng.model.AnalysisUpdateTagsRequest;
import ai.reveng.model.AppApiRestV2AnalysesEnumsOrderBy;
import ai.reveng.model.BaseResponse;
import ai.reveng.model.BaseResponseAnalysisCreateResponse;
import ai.reveng.model.BaseResponseAnalysisDetailResponse;
import ai.reveng.model.BaseResponseAnalysisFunctionMapping;
import ai.reveng.model.BaseResponseAnalysisUpdateTagsResponse;
import ai.reveng.model.BaseResponseBasic;
import ai.reveng.model.BaseResponseCreated;
import ai.reveng.model.BaseResponseDict;
import ai.reveng.model.BaseResponseLogs;
import ai.reveng.model.BaseResponseParams;
import ai.reveng.model.BaseResponseRecent;
import ai.reveng.model.BaseResponseStatus;
import ai.reveng.model.BaseResponseUploadResponse;
import ai.reveng.model.DynamicExecutionStatusInput;
import java.io.File;
import ai.reveng.model.ModelName;
import ai.reveng.model.Order;
import ai.reveng.model.ReAnalysisForm;
import ai.reveng.model.StatusInput;
import ai.reveng.model.UploadFileType;
import ai.reveng.model.Workspace;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AnalysesCoreApi
 */
@Disabled
public class AnalysesCoreApiTest {

    private final AnalysesCoreApi api = new AnalysesCoreApi();

    /**
     * Create Analysis
     *
     * Begins an analysis
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAnalysisTest() throws ApiException {
        AnalysisCreateRequest analysisCreateRequest = null;
        String xRevEngApplication = null;
        BaseResponseAnalysisCreateResponse response = api.createAnalysis(analysisCreateRequest, xRevEngApplication);
        // TODO: test validations
    }

    /**
     * Delete Analysis
     *
     * Deletes an analysis based on the provided analysis ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAnalysisTest() throws ApiException {
        Integer analysisId = null;
        BaseResponseDict response = api.deleteAnalysis(analysisId);
        // TODO: test validations
    }

    /**
     * Gets basic analysis information
     *
     * Returns basic analysis information for an analysis
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAnalysisBasicInfoTest() throws ApiException {
        Integer analysisId = null;
        BaseResponseBasic response = api.getAnalysisBasicInfo(analysisId);
        // TODO: test validations
    }

    /**
     * Get Analysis Function Map
     *
     * Returns three maps: a map of function ids to function addresses, it&#39;s inverse and a map of function addresses to function names.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAnalysisFunctionMapTest() throws ApiException {
        Integer analysisId = null;
        BaseResponseAnalysisFunctionMapping response = api.getAnalysisFunctionMap(analysisId);
        // TODO: test validations
    }

    /**
     * Gets the logs of an analysis
     *
     * Given an analysis ID gets the current logs of an analysis
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAnalysisLogsTest() throws ApiException {
        Integer analysisId = null;
        BaseResponseLogs response = api.getAnalysisLogs(analysisId);
        // TODO: test validations
    }

    /**
     * Gets analysis param information
     *
     * Gets the params that the analysis was run with
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAnalysisParamsTest() throws ApiException {
        Integer analysisId = null;
        BaseResponseParams response = api.getAnalysisParams(analysisId);
        // TODO: test validations
    }

    /**
     * Gets the status of an analysis
     *
     * Given an analysis ID gets the current status of the analysis
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAnalysisStatusTest() throws ApiException {
        Integer analysisId = null;
        BaseResponseStatus response = api.getAnalysisStatus(analysisId);
        // TODO: test validations
    }

    /**
     * Gets the most recent analyses
     *
     * Gets the most recent analyses provided a scope, this is then paginated, if pages and limit doesnt fit, it increases the limit
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAnalysesTest() throws ApiException {
        String searchTerm = null;
        List<Workspace> workspace = null;
        List<StatusInput> status = null;
        List<ModelName> modelName = null;
        DynamicExecutionStatusInput dynamicExecutionStatus = null;
        List<String> usernames = null;
        String sha256Hash = null;
        Integer limit = null;
        Integer offset = null;
        AppApiRestV2AnalysesEnumsOrderBy orderBy = null;
        Order order = null;
        BaseResponseRecent response = api.listAnalyses(searchTerm, workspace, status, modelName, dynamicExecutionStatus, usernames, sha256Hash, limit, offset, orderBy, order);
        // TODO: test validations
    }

    /**
     * Gets the analysis ID from binary ID
     *
     * Given an binary ID gets the ID of an analysis
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void lookupBinaryIdTest() throws ApiException {
        Integer binaryId = null;
        Object response = api.lookupBinaryId(binaryId);
        // TODO: test validations
    }

    /**
     * Requeue Analysis
     *
     * Re-queues an already uploaded analysis
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void requeueAnalysisTest() throws ApiException {
        Integer analysisId = null;
        ReAnalysisForm reAnalysisForm = null;
        String xRevEngApplication = null;
        BaseResponseCreated response = api.requeueAnalysis(analysisId, reAnalysisForm, xRevEngApplication);
        // TODO: test validations
    }

    /**
     * Update Analysis
     *
     * Updates analysis attributes (binary_name, analysis_scope). User must be the owner.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAnalysisTest() throws ApiException {
        Integer analysisId = null;
        AnalysisUpdateRequest analysisUpdateRequest = null;
        BaseResponseAnalysisDetailResponse response = api.updateAnalysis(analysisId, analysisUpdateRequest);
        // TODO: test validations
    }

    /**
     * Update Analysis Tags
     *
     * Updates analysis tags. User must be the owner.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAnalysisTagsTest() throws ApiException {
        Integer analysisId = null;
        AnalysisUpdateTagsRequest analysisUpdateTagsRequest = null;
        BaseResponseAnalysisUpdateTagsResponse response = api.updateAnalysisTags(analysisId, analysisUpdateTagsRequest);
        // TODO: test validations
    }

    /**
     * Upload File
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadFileTest() throws ApiException {
        UploadFileType uploadFileType = null;
        File _file = null;
        String packedPassword = null;
        Boolean forceOverwrite = null;
        BaseResponseUploadResponse response = api.uploadFile(uploadFileType, _file, packedPassword, forceOverwrite);
        // TODO: test validations
    }

}
