/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.api;

import ai.reveng.invoker.ApiException;
import ai.reveng.model.BaseResponse;
import java.io.File;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FirmwareApi
 */
@Disabled
public class FirmwareApiTest {

    private final FirmwareApi api = new FirmwareApi();

    /**
     * Upload firmware for unpacking
     *
     * Uploads a firmware file and begins a &#39;Firmware Unpacker&#39; task. Returns a result identifier, which can be used to poll for the response.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBinariesForFirmwareTaskTest() throws ApiException {
        String taskId = null;
        String apiKey = null;
        Object response = api.getBinariesForFirmwareTask(taskId, apiKey);
        // TODO: test validations
    }

    /**
     * Upload firmware for unpacking
     *
     * Uploads a firmware file and begins a &#39;Firmware Unpacker&#39; task. Returns a result identifier, which can be used to poll for the response.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadFirmwareTest() throws ApiException {
        File _file = null;
        String apiKey = null;
        String password = null;
        Object response = api.uploadFirmware(_file, apiKey, password);
        // TODO: test validations
    }

}
