/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * The version of the OpenAPI document: v1.92.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.api;

import ai.reveng.invoker.ApiException;
import ai.reveng.model.AiUnstripRequest;
import ai.reveng.model.AnalysisFunctionMatchingRequest;
import ai.reveng.model.AutoUnstripRequest;
import ai.reveng.model.AutoUnstripResponse;
import ai.reveng.model.BaseResponse;
import ai.reveng.model.BaseResponseAnalysisStringsResponse;
import ai.reveng.model.BaseResponseCalleesCallerFunctionsResponse;
import ai.reveng.model.BaseResponseFunctionBlocksResponse;
import ai.reveng.model.BaseResponseFunctionCapabilityResponse;
import ai.reveng.model.BaseResponseFunctionStringsResponse;
import ai.reveng.model.BaseResponseFunctionsDetailResponse;
import ai.reveng.model.BaseResponseListSimilarFunctionsResponse;
import java.math.BigDecimal;
import ai.reveng.model.FunctionMatchingBatchResponse;
import ai.reveng.model.FunctionMatchingRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FunctionsCoreApi
 */
@Disabled
public class FunctionsCoreApiTest {

    private final FunctionsCoreApi api = new FunctionsCoreApi();

    /**
     * Performs matching and auto-unstrip for an analysis and its functions
     *
     * Takes in the analysis ID, uses the functions ID&#39;s from it and settings to find the nearest function groups for each function that&#39;s within the system
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void aiUnstripTest() throws ApiException {
        Integer analysisId = null;
        AiUnstripRequest aiUnstripRequest = null;
        String authorization = null;
        AutoUnstripResponse response = api.aiUnstrip(analysisId, aiUnstripRequest, authorization);
        // TODO: test validations
    }

    /**
     * Perform matching for the functions of an analysis
     *
     * Takes in an analysis id and settings and matches the nearest functions to the ones associated with it. Results can optionally be filtered by collection, binary, debug type or (other) function ids
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void analysisFunctionMatchingTest() throws ApiException {
        Integer analysisId = null;
        AnalysisFunctionMatchingRequest analysisFunctionMatchingRequest = null;
        String authorization = null;
        FunctionMatchingBatchResponse response = api.analysisFunctionMatching(analysisId, analysisFunctionMatchingRequest, authorization);
        // TODO: test validations
    }

    /**
     * Performs matching and auto-unstrip for an analysis and its functions
     *
     * Takes in the analysis ID, uses the functions ID&#39;s from it and settings to find the nearest function for each function that&#39;s within the system
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void autoUnstripTest() throws ApiException {
        Integer analysisId = null;
        AutoUnstripRequest autoUnstripRequest = null;
        String authorization = null;
        AutoUnstripResponse response = api.autoUnstrip(analysisId, autoUnstripRequest, authorization);
        // TODO: test validations
    }

    /**
     * Perform function matching for an arbitrary batch of functions, binaries or collections
     *
     * Takes in an input of functions ID&#39;s and settings and finds the nearest functions for each function that&#39;s within the system
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void batchFunctionMatchingTest() throws ApiException {
        FunctionMatchingRequest functionMatchingRequest = null;
        String authorization = null;
        FunctionMatchingBatchResponse response = api.batchFunctionMatching(functionMatchingRequest, authorization);
        // TODO: test validations
    }

    /**
     * Cancels a running ai-unstrip
     *
     * Takes in the analysis ID and cancels a running ai-unstrip operation
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelAiUnstripTest() throws ApiException {
        Integer analysisId = null;
        String authorization = null;
        AutoUnstripResponse response = api.cancelAiUnstrip(analysisId, authorization);
        // TODO: test validations
    }

    /**
     * Cancels a running auto-unstrip
     *
     * Takes in the analysis ID and cancels a running auto-unstrip operation
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelAutoUnstripTest() throws ApiException {
        Integer analysisId = null;
        String authorization = null;
        AutoUnstripResponse response = api.cancelAutoUnstrip(analysisId, authorization);
        // TODO: test validations
    }

    /**
     * Get string information found in the Analysis
     *
     * Get string information found in the analysis
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAnalysisStringsTest() throws ApiException {
        Integer analysisId = null;
        Integer page = null;
        Integer pageSize = null;
        String search = null;
        String functionSearch = null;
        String authorization = null;
        BaseResponseAnalysisStringsResponse response = api.getAnalysisStrings(analysisId, page, pageSize, search, functionSearch, authorization);
        // TODO: test validations
    }

    /**
     * Get disassembly blocks related to the function
     *
     * Get disassembly blocks related to the function
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFunctionBlocksTest() throws ApiException {
        Integer functionId = null;
        String authorization = null;
        BaseResponseFunctionBlocksResponse response = api.getFunctionBlocks(functionId, authorization);
        // TODO: test validations
    }

    /**
     * Get list of functions that call or are called by the specified function
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFunctionCalleesCallersTest() throws ApiException {
        Integer functionId = null;
        String authorization = null;
        BaseResponseCalleesCallerFunctionsResponse response = api.getFunctionCalleesCallers(functionId, authorization);
        // TODO: test validations
    }

    /**
     * Retrieve a functions capabilities
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFunctionCapabilitiesTest() throws ApiException {
        Integer functionId = null;
        String authorization = null;
        BaseResponseFunctionCapabilityResponse response = api.getFunctionCapabilities(functionId, authorization);
        // TODO: test validations
    }

    /**
     * Get function details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFunctionDetailsTest() throws ApiException {
        Integer functionId = null;
        String authorization = null;
        BaseResponseFunctionsDetailResponse response = api.getFunctionDetails(functionId, authorization);
        // TODO: test validations
    }

    /**
     * Get string information found in the function
     *
     * Get string information found in the function
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFunctionStringsTest() throws ApiException {
        Integer functionId = null;
        Integer page = null;
        Integer pageSize = null;
        String search = null;
        String authorization = null;
        BaseResponseFunctionStringsResponse response = api.getFunctionStrings(functionId, page, pageSize, search, authorization);
        // TODO: test validations
    }

    /**
     * Get list of similar functions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSimilarFunctionsTest() throws ApiException {
        Integer functionId = null;
        Integer limit = null;
        BigDecimal distance = null;
        List<Integer> collectionIds = null;
        Boolean debug = null;
        List<String> debugTypes = null;
        List<Integer> binaryIds = null;
        String authorization = null;
        BaseResponseListSimilarFunctionsResponse response = api.getSimilarFunctions(functionId, limit, distance, collectionIds, debug, debugTypes, binaryIds, authorization);
        // TODO: test validations
    }

}
