/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import java.util.Locale;
import ai.reveng.model.FunctionMatchingFilters;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import ai.reveng.invoker.JSON;

/**
 * AnalysisFunctionMatchingRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AnalysisFunctionMatchingRequest {
  public static final String SERIALIZED_NAME_MIN_SIMILARITY = "min_similarity";
  @SerializedName(SERIALIZED_NAME_MIN_SIMILARITY)
  @javax.annotation.Nullable
  private BigDecimal minSimilarity = new BigDecimal("90.0");

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  @javax.annotation.Nullable
  private FunctionMatchingFilters filters;

  public static final String SERIALIZED_NAME_RESULTS_PER_FUNCTION = "results_per_function";
  @SerializedName(SERIALIZED_NAME_RESULTS_PER_FUNCTION)
  @javax.annotation.Nullable
  private Integer resultsPerFunction = 1;

  public static final String SERIALIZED_NAME_PAGE = "page";
  @SerializedName(SERIALIZED_NAME_PAGE)
  @javax.annotation.Nullable
  private Integer page = 1;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "page_size";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  @javax.annotation.Nullable
  private Integer pageSize = 0;

  public AnalysisFunctionMatchingRequest() {
  }

  public AnalysisFunctionMatchingRequest minSimilarity(@javax.annotation.Nullable BigDecimal minSimilarity) {
    this.minSimilarity = minSimilarity;
    return this;
  }

  /**
   * Minimum similarity expected for a match as a percentage, default is 90
   * minimum: 0.0
   * maximum: 100.0
   * @return minSimilarity
   */
  @javax.annotation.Nullable
  public BigDecimal getMinSimilarity() {
    return minSimilarity;
  }

  public void setMinSimilarity(@javax.annotation.Nullable BigDecimal minSimilarity) {
    this.minSimilarity = minSimilarity;
  }


  public AnalysisFunctionMatchingRequest filters(@javax.annotation.Nullable FunctionMatchingFilters filters) {
    this.filters = filters;
    return this;
  }

  /**
   * Get filters
   * @return filters
   */
  @javax.annotation.Nullable
  public FunctionMatchingFilters getFilters() {
    return filters;
  }

  public void setFilters(@javax.annotation.Nullable FunctionMatchingFilters filters) {
    this.filters = filters;
  }


  public AnalysisFunctionMatchingRequest resultsPerFunction(@javax.annotation.Nullable Integer resultsPerFunction) {
    this.resultsPerFunction = resultsPerFunction;
    return this;
  }

  /**
   * Maximum number of matches to return per function, default is 1, max is 10
   * minimum: 1
   * maximum: 10
   * @return resultsPerFunction
   */
  @javax.annotation.Nullable
  public Integer getResultsPerFunction() {
    return resultsPerFunction;
  }

  public void setResultsPerFunction(@javax.annotation.Nullable Integer resultsPerFunction) {
    this.resultsPerFunction = resultsPerFunction;
  }


  public AnalysisFunctionMatchingRequest page(@javax.annotation.Nullable Integer page) {
    this.page = page;
    return this;
  }

  /**
   * Page number for paginated results, default is 1 (first page)
   * minimum: 1
   * @return page
   */
  @javax.annotation.Nullable
  public Integer getPage() {
    return page;
  }

  public void setPage(@javax.annotation.Nullable Integer page) {
    this.page = page;
  }


  public AnalysisFunctionMatchingRequest pageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * Number of functions to return per page, default is 0 (all functions), max is 1000
   * minimum: 0
   * maximum: 1000
   * @return pageSize
   */
  @javax.annotation.Nullable
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AnalysisFunctionMatchingRequest instance itself
   */
  public AnalysisFunctionMatchingRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalysisFunctionMatchingRequest analysisFunctionMatchingRequest = (AnalysisFunctionMatchingRequest) o;
    return Objects.equals(this.minSimilarity, analysisFunctionMatchingRequest.minSimilarity) &&
        Objects.equals(this.filters, analysisFunctionMatchingRequest.filters) &&
        Objects.equals(this.resultsPerFunction, analysisFunctionMatchingRequest.resultsPerFunction) &&
        Objects.equals(this.page, analysisFunctionMatchingRequest.page) &&
        Objects.equals(this.pageSize, analysisFunctionMatchingRequest.pageSize)&&
        Objects.equals(this.additionalProperties, analysisFunctionMatchingRequest.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(minSimilarity, filters, resultsPerFunction, page, pageSize, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalysisFunctionMatchingRequest {\n");
    sb.append("    minSimilarity: ").append(toIndentedString(minSimilarity)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    resultsPerFunction: ").append(toIndentedString(resultsPerFunction)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("min_similarity", "filters", "results_per_function", "page", "page_size"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AnalysisFunctionMatchingRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AnalysisFunctionMatchingRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in AnalysisFunctionMatchingRequest is not found in the empty JSON string", AnalysisFunctionMatchingRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `filters`
      if (jsonObj.get("filters") != null && !jsonObj.get("filters").isJsonNull()) {
        FunctionMatchingFilters.validateJsonElement(jsonObj.get("filters"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AnalysisFunctionMatchingRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AnalysisFunctionMatchingRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AnalysisFunctionMatchingRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AnalysisFunctionMatchingRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AnalysisFunctionMatchingRequest>() {
           @Override
           public void write(JsonWriter out, AnalysisFunctionMatchingRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AnalysisFunctionMatchingRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AnalysisFunctionMatchingRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AnalysisFunctionMatchingRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AnalysisFunctionMatchingRequest
   * @throws IOException if the JSON string is invalid with respect to AnalysisFunctionMatchingRequest
   */
  public static AnalysisFunctionMatchingRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AnalysisFunctionMatchingRequest.class);
  }

  /**
   * Convert an instance of AnalysisFunctionMatchingRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

