/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.reveng.invoker.JSON;

/**
 * Basic
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-26T15:37:47.583998+01:00[Europe/London]", comments = "Generator version: 7.15.0")
public class Basic {
  public static final String SERIALIZED_NAME_BINARY_NAME = "binary_name";
  @SerializedName(SERIALIZED_NAME_BINARY_NAME)
  @javax.annotation.Nonnull
  private String binaryName;

  public static final String SERIALIZED_NAME_BINARY_SIZE = "binary_size";
  @SerializedName(SERIALIZED_NAME_BINARY_SIZE)
  @javax.annotation.Nonnull
  private Integer binarySize;

  public static final String SERIALIZED_NAME_CREATION = "creation";
  @SerializedName(SERIALIZED_NAME_CREATION)
  @javax.annotation.Nonnull
  private OffsetDateTime creation;

  public static final String SERIALIZED_NAME_SHA256_HASH = "sha_256_hash";
  @SerializedName(SERIALIZED_NAME_SHA256_HASH)
  @javax.annotation.Nonnull
  private String sha256Hash;

  public static final String SERIALIZED_NAME_MODEL_NAME = "model_name";
  @SerializedName(SERIALIZED_NAME_MODEL_NAME)
  @javax.annotation.Nonnull
  private String modelName;

  public static final String SERIALIZED_NAME_OWNER_USERNAME = "owner_username";
  @SerializedName(SERIALIZED_NAME_OWNER_USERNAME)
  @javax.annotation.Nonnull
  private String ownerUsername;

  public static final String SERIALIZED_NAME_ANALYSIS_SCOPE = "analysis_scope";
  @SerializedName(SERIALIZED_NAME_ANALYSIS_SCOPE)
  @javax.annotation.Nonnull
  private String analysisScope;

  public static final String SERIALIZED_NAME_IS_OWNER = "is_owner";
  @SerializedName(SERIALIZED_NAME_IS_OWNER)
  @javax.annotation.Nonnull
  private Boolean isOwner;

  public static final String SERIALIZED_NAME_DEBUG = "debug";
  @SerializedName(SERIALIZED_NAME_DEBUG)
  @javax.annotation.Nonnull
  private Boolean debug;

  public static final String SERIALIZED_NAME_FUNCTION_COUNT = "function_count";
  @SerializedName(SERIALIZED_NAME_FUNCTION_COUNT)
  @javax.annotation.Nonnull
  private Integer functionCount;

  public static final String SERIALIZED_NAME_IS_ADVANCED = "is_advanced";
  @SerializedName(SERIALIZED_NAME_IS_ADVANCED)
  @javax.annotation.Nonnull
  private Boolean isAdvanced;

  public static final String SERIALIZED_NAME_BASE_ADDRESS = "base_address";
  @SerializedName(SERIALIZED_NAME_BASE_ADDRESS)
  @javax.annotation.Nullable
  private Integer baseAddress;

  public Basic() {
  }

  public Basic binaryName(@javax.annotation.Nonnull String binaryName) {
    this.binaryName = binaryName;
    return this;
  }

  /**
   * The name of the binary uploaded
   * @return binaryName
   */
  @javax.annotation.Nonnull
  public String getBinaryName() {
    return binaryName;
  }

  public void setBinaryName(@javax.annotation.Nonnull String binaryName) {
    this.binaryName = binaryName;
  }


  public Basic binarySize(@javax.annotation.Nonnull Integer binarySize) {
    this.binarySize = binarySize;
    return this;
  }

  /**
   * The size of the binary uploaded (bytes)
   * @return binarySize
   */
  @javax.annotation.Nonnull
  public Integer getBinarySize() {
    return binarySize;
  }

  public void setBinarySize(@javax.annotation.Nonnull Integer binarySize) {
    this.binarySize = binarySize;
  }


  public Basic creation(@javax.annotation.Nonnull OffsetDateTime creation) {
    this.creation = creation;
    return this;
  }

  /**
   * When the binary was uploaded
   * @return creation
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreation() {
    return creation;
  }

  public void setCreation(@javax.annotation.Nonnull OffsetDateTime creation) {
    this.creation = creation;
  }


  public Basic sha256Hash(@javax.annotation.Nonnull String sha256Hash) {
    this.sha256Hash = sha256Hash;
    return this;
  }

  /**
   * The hash of the binary uploaded
   * @return sha256Hash
   */
  @javax.annotation.Nonnull
  public String getSha256Hash() {
    return sha256Hash;
  }

  public void setSha256Hash(@javax.annotation.Nonnull String sha256Hash) {
    this.sha256Hash = sha256Hash;
  }


  public Basic modelName(@javax.annotation.Nonnull String modelName) {
    this.modelName = modelName;
    return this;
  }

  /**
   * The model name used for analysis
   * @return modelName
   */
  @javax.annotation.Nonnull
  public String getModelName() {
    return modelName;
  }

  public void setModelName(@javax.annotation.Nonnull String modelName) {
    this.modelName = modelName;
  }


  public Basic ownerUsername(@javax.annotation.Nonnull String ownerUsername) {
    this.ownerUsername = ownerUsername;
    return this;
  }

  /**
   * The name of the owner of the binary
   * @return ownerUsername
   */
  @javax.annotation.Nonnull
  public String getOwnerUsername() {
    return ownerUsername;
  }

  public void setOwnerUsername(@javax.annotation.Nonnull String ownerUsername) {
    this.ownerUsername = ownerUsername;
  }


  public Basic analysisScope(@javax.annotation.Nonnull String analysisScope) {
    this.analysisScope = analysisScope;
    return this;
  }

  /**
   * The scope of the analysis
   * @return analysisScope
   */
  @javax.annotation.Nonnull
  public String getAnalysisScope() {
    return analysisScope;
  }

  public void setAnalysisScope(@javax.annotation.Nonnull String analysisScope) {
    this.analysisScope = analysisScope;
  }


  public Basic isOwner(@javax.annotation.Nonnull Boolean isOwner) {
    this.isOwner = isOwner;
    return this;
  }

  /**
   * Whether the current user is the owner
   * @return isOwner
   */
  @javax.annotation.Nonnull
  public Boolean getIsOwner() {
    return isOwner;
  }

  public void setIsOwner(@javax.annotation.Nonnull Boolean isOwner) {
    this.isOwner = isOwner;
  }


  public Basic debug(@javax.annotation.Nonnull Boolean debug) {
    this.debug = debug;
    return this;
  }

  /**
   * Whether the current analysis was analysed with debug symbols
   * @return debug
   */
  @javax.annotation.Nonnull
  public Boolean getDebug() {
    return debug;
  }

  public void setDebug(@javax.annotation.Nonnull Boolean debug) {
    this.debug = debug;
  }


  public Basic functionCount(@javax.annotation.Nonnull Integer functionCount) {
    this.functionCount = functionCount;
    return this;
  }

  /**
   * The number of functions in the binary
   * @return functionCount
   */
  @javax.annotation.Nonnull
  public Integer getFunctionCount() {
    return functionCount;
  }

  public void setFunctionCount(@javax.annotation.Nonnull Integer functionCount) {
    this.functionCount = functionCount;
  }


  public Basic isAdvanced(@javax.annotation.Nonnull Boolean isAdvanced) {
    this.isAdvanced = isAdvanced;
    return this;
  }

  /**
   * Whether the analysis was advanced
   * @return isAdvanced
   */
  @javax.annotation.Nonnull
  public Boolean getIsAdvanced() {
    return isAdvanced;
  }

  public void setIsAdvanced(@javax.annotation.Nonnull Boolean isAdvanced) {
    this.isAdvanced = isAdvanced;
  }


  public Basic baseAddress(@javax.annotation.Nullable Integer baseAddress) {
    this.baseAddress = baseAddress;
    return this;
  }

  /**
   * Get baseAddress
   * @return baseAddress
   */
  @javax.annotation.Nullable
  public Integer getBaseAddress() {
    return baseAddress;
  }

  public void setBaseAddress(@javax.annotation.Nullable Integer baseAddress) {
    this.baseAddress = baseAddress;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Basic basic = (Basic) o;
    return Objects.equals(this.binaryName, basic.binaryName) &&
        Objects.equals(this.binarySize, basic.binarySize) &&
        Objects.equals(this.creation, basic.creation) &&
        Objects.equals(this.sha256Hash, basic.sha256Hash) &&
        Objects.equals(this.modelName, basic.modelName) &&
        Objects.equals(this.ownerUsername, basic.ownerUsername) &&
        Objects.equals(this.analysisScope, basic.analysisScope) &&
        Objects.equals(this.isOwner, basic.isOwner) &&
        Objects.equals(this.debug, basic.debug) &&
        Objects.equals(this.functionCount, basic.functionCount) &&
        Objects.equals(this.isAdvanced, basic.isAdvanced) &&
        Objects.equals(this.baseAddress, basic.baseAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(binaryName, binarySize, creation, sha256Hash, modelName, ownerUsername, analysisScope, isOwner, debug, functionCount, isAdvanced, baseAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Basic {\n");
    sb.append("    binaryName: ").append(toIndentedString(binaryName)).append("\n");
    sb.append("    binarySize: ").append(toIndentedString(binarySize)).append("\n");
    sb.append("    creation: ").append(toIndentedString(creation)).append("\n");
    sb.append("    sha256Hash: ").append(toIndentedString(sha256Hash)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    ownerUsername: ").append(toIndentedString(ownerUsername)).append("\n");
    sb.append("    analysisScope: ").append(toIndentedString(analysisScope)).append("\n");
    sb.append("    isOwner: ").append(toIndentedString(isOwner)).append("\n");
    sb.append("    debug: ").append(toIndentedString(debug)).append("\n");
    sb.append("    functionCount: ").append(toIndentedString(functionCount)).append("\n");
    sb.append("    isAdvanced: ").append(toIndentedString(isAdvanced)).append("\n");
    sb.append("    baseAddress: ").append(toIndentedString(baseAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("binary_name", "binary_size", "creation", "sha_256_hash", "model_name", "owner_username", "analysis_scope", "is_owner", "debug", "function_count", "is_advanced", "base_address"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("binary_name", "binary_size", "creation", "sha_256_hash", "model_name", "owner_username", "analysis_scope", "is_owner", "debug", "function_count", "is_advanced", "base_address"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Basic
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Basic.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Basic is not found in the empty JSON string", Basic.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Basic.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Basic` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Basic.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("binary_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `binary_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("binary_name").toString()));
      }
      if (!jsonObj.get("sha_256_hash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sha_256_hash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sha_256_hash").toString()));
      }
      if (!jsonObj.get("model_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `model_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model_name").toString()));
      }
      if (!jsonObj.get("owner_username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `owner_username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner_username").toString()));
      }
      if (!jsonObj.get("analysis_scope").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `analysis_scope` to be a primitive type in the JSON string but got `%s`", jsonObj.get("analysis_scope").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Basic.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Basic' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Basic> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Basic.class));

       return (TypeAdapter<T>) new TypeAdapter<Basic>() {
           @Override
           public void write(JsonWriter out, Basic value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Basic read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Basic given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Basic
   * @throws IOException if the JSON string is invalid with respect to Basic
   */
  public static Basic fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Basic.class);
  }

  /**
   * Convert an instance of Basic to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

