/*
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import ai.reveng.invoker.JSON;

/**
 * BinaryExternalsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BinaryExternalsResponse {
  public static final String SERIALIZED_NAME_MB = "mb";
  @SerializedName(SERIALIZED_NAME_MB)
  @javax.annotation.Nonnull
  private Map<String, Object> mb = new HashMap<>();

  public static final String SERIALIZED_NAME_MB_LAST_UPDATED = "mb_last_updated";
  @SerializedName(SERIALIZED_NAME_MB_LAST_UPDATED)
  @javax.annotation.Nonnull
  private OffsetDateTime mbLastUpdated;

  public static final String SERIALIZED_NAME_SHA256_HASH = "sha_256_hash";
  @SerializedName(SERIALIZED_NAME_SHA256_HASH)
  @javax.annotation.Nonnull
  private String sha256Hash;

  public static final String SERIALIZED_NAME_VT = "vt";
  @SerializedName(SERIALIZED_NAME_VT)
  @javax.annotation.Nonnull
  private Map<String, Object> vt = new HashMap<>();

  public static final String SERIALIZED_NAME_VT_LAST_UPDATED = "vt_last_updated";
  @SerializedName(SERIALIZED_NAME_VT_LAST_UPDATED)
  @javax.annotation.Nonnull
  private OffsetDateTime vtLastUpdated;

  public BinaryExternalsResponse() {
  }

  public BinaryExternalsResponse mb(@javax.annotation.Nonnull Map<String, Object> mb) {
    this.mb = mb;
    return this;
  }

  public BinaryExternalsResponse putMbItem(String key, Object mbItem) {
    if (this.mb == null) {
      this.mb = new HashMap<>();
    }
    this.mb.put(key, mbItem);
    return this;
  }

  /**
   * MalwareBazaar information
   * @return mb
   */
  @javax.annotation.Nonnull
  public Map<String, Object> getMb() {
    return mb;
  }

  public void setMb(@javax.annotation.Nonnull Map<String, Object> mb) {
    this.mb = mb;
  }


  public BinaryExternalsResponse mbLastUpdated(@javax.annotation.Nonnull OffsetDateTime mbLastUpdated) {
    this.mbLastUpdated = mbLastUpdated;
    return this;
  }

  /**
   * MalwareBazaar last updated date
   * @return mbLastUpdated
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getMbLastUpdated() {
    return mbLastUpdated;
  }

  public void setMbLastUpdated(@javax.annotation.Nonnull OffsetDateTime mbLastUpdated) {
    this.mbLastUpdated = mbLastUpdated;
  }


  public BinaryExternalsResponse sha256Hash(@javax.annotation.Nonnull String sha256Hash) {
    this.sha256Hash = sha256Hash;
    return this;
  }

  /**
   * SHA256 hash of the binary
   * @return sha256Hash
   */
  @javax.annotation.Nonnull
  public String getSha256Hash() {
    return sha256Hash;
  }

  public void setSha256Hash(@javax.annotation.Nonnull String sha256Hash) {
    this.sha256Hash = sha256Hash;
  }


  public BinaryExternalsResponse vt(@javax.annotation.Nonnull Map<String, Object> vt) {
    this.vt = vt;
    return this;
  }

  public BinaryExternalsResponse putVtItem(String key, Object vtItem) {
    if (this.vt == null) {
      this.vt = new HashMap<>();
    }
    this.vt.put(key, vtItem);
    return this;
  }

  /**
   * VirusTotal information
   * @return vt
   */
  @javax.annotation.Nonnull
  public Map<String, Object> getVt() {
    return vt;
  }

  public void setVt(@javax.annotation.Nonnull Map<String, Object> vt) {
    this.vt = vt;
  }


  public BinaryExternalsResponse vtLastUpdated(@javax.annotation.Nonnull OffsetDateTime vtLastUpdated) {
    this.vtLastUpdated = vtLastUpdated;
    return this;
  }

  /**
   * VirusTotal last updated date
   * @return vtLastUpdated
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getVtLastUpdated() {
    return vtLastUpdated;
  }

  public void setVtLastUpdated(@javax.annotation.Nonnull OffsetDateTime vtLastUpdated) {
    this.vtLastUpdated = vtLastUpdated;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BinaryExternalsResponse instance itself
   */
  public BinaryExternalsResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BinaryExternalsResponse binaryExternalsResponse = (BinaryExternalsResponse) o;
    return Objects.equals(this.mb, binaryExternalsResponse.mb) &&
        Objects.equals(this.mbLastUpdated, binaryExternalsResponse.mbLastUpdated) &&
        Objects.equals(this.sha256Hash, binaryExternalsResponse.sha256Hash) &&
        Objects.equals(this.vt, binaryExternalsResponse.vt) &&
        Objects.equals(this.vtLastUpdated, binaryExternalsResponse.vtLastUpdated)&&
        Objects.equals(this.additionalProperties, binaryExternalsResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mb, mbLastUpdated, sha256Hash, vt, vtLastUpdated, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BinaryExternalsResponse {\n");
    sb.append("    mb: ").append(toIndentedString(mb)).append("\n");
    sb.append("    mbLastUpdated: ").append(toIndentedString(mbLastUpdated)).append("\n");
    sb.append("    sha256Hash: ").append(toIndentedString(sha256Hash)).append("\n");
    sb.append("    vt: ").append(toIndentedString(vt)).append("\n");
    sb.append("    vtLastUpdated: ").append(toIndentedString(vtLastUpdated)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("mb", "mb_last_updated", "sha_256_hash", "vt", "vt_last_updated"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("mb", "mb_last_updated", "sha_256_hash", "vt", "vt_last_updated"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BinaryExternalsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BinaryExternalsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in BinaryExternalsResponse is not found in the empty JSON string", BinaryExternalsResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BinaryExternalsResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("sha_256_hash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sha_256_hash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sha_256_hash").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BinaryExternalsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BinaryExternalsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BinaryExternalsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BinaryExternalsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<BinaryExternalsResponse>() {
           @Override
           public void write(JsonWriter out, BinaryExternalsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public BinaryExternalsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             BinaryExternalsResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BinaryExternalsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BinaryExternalsResponse
   * @throws IOException if the JSON string is invalid with respect to BinaryExternalsResponse
   */
  public static BinaryExternalsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BinaryExternalsResponse.class);
  }

  /**
   * Convert an instance of BinaryExternalsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

