/*
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import ai.reveng.invoker.JSON;

/**
 * CollectionListItemBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CollectionListItemBody {
  public static final String SERIALIZED_NAME_COLLECTION_ID = "collection_id";
  @SerializedName(SERIALIZED_NAME_COLLECTION_ID)
  @javax.annotation.Nonnull
  private Long collectionId;

  public static final String SERIALIZED_NAME_COLLECTION_NAME = "collection_name";
  @SerializedName(SERIALIZED_NAME_COLLECTION_NAME)
  @javax.annotation.Nonnull
  private String collectionName;

  public static final String SERIALIZED_NAME_COLLECTION_OWNER = "collection_owner";
  @SerializedName(SERIALIZED_NAME_COLLECTION_OWNER)
  @javax.annotation.Nonnull
  private String collectionOwner;

  public static final String SERIALIZED_NAME_COLLECTION_SCOPE = "collection_scope";
  @SerializedName(SERIALIZED_NAME_COLLECTION_SCOPE)
  @javax.annotation.Nonnull
  private String collectionScope;

  public static final String SERIALIZED_NAME_COLLECTION_SIZE = "collection_size";
  @SerializedName(SERIALIZED_NAME_COLLECTION_SIZE)
  @javax.annotation.Nonnull
  private Long collectionSize;

  public static final String SERIALIZED_NAME_COLLECTION_TAGS = "collection_tags";
  @SerializedName(SERIALIZED_NAME_COLLECTION_TAGS)
  @javax.annotation.Nullable
  private List<String> collectionTags;

  public static final String SERIALIZED_NAME_CREATION = "creation";
  @SerializedName(SERIALIZED_NAME_CREATION)
  @javax.annotation.Nonnull
  private OffsetDateTime creation;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nonnull
  private String description;

  public static final String SERIALIZED_NAME_MODEL_NAME = "model_name";
  @SerializedName(SERIALIZED_NAME_MODEL_NAME)
  @javax.annotation.Nonnull
  private String modelName;

  public static final String SERIALIZED_NAME_OFFICIAL_COLLECTION = "official_collection";
  @SerializedName(SERIALIZED_NAME_OFFICIAL_COLLECTION)
  @javax.annotation.Nonnull
  private Boolean officialCollection;

  public static final String SERIALIZED_NAME_TEAM_ID = "team_id";
  @SerializedName(SERIALIZED_NAME_TEAM_ID)
  @javax.annotation.Nonnull
  private Long teamId;

  public CollectionListItemBody() {
  }

  public CollectionListItemBody collectionId(@javax.annotation.Nonnull Long collectionId) {
    this.collectionId = collectionId;
    return this;
  }

  /**
   * Get collectionId
   * @return collectionId
   */
  @javax.annotation.Nonnull
  public Long getCollectionId() {
    return collectionId;
  }

  public void setCollectionId(@javax.annotation.Nonnull Long collectionId) {
    this.collectionId = collectionId;
  }


  public CollectionListItemBody collectionName(@javax.annotation.Nonnull String collectionName) {
    this.collectionName = collectionName;
    return this;
  }

  /**
   * Get collectionName
   * @return collectionName
   */
  @javax.annotation.Nonnull
  public String getCollectionName() {
    return collectionName;
  }

  public void setCollectionName(@javax.annotation.Nonnull String collectionName) {
    this.collectionName = collectionName;
  }


  public CollectionListItemBody collectionOwner(@javax.annotation.Nonnull String collectionOwner) {
    this.collectionOwner = collectionOwner;
    return this;
  }

  /**
   * Get collectionOwner
   * @return collectionOwner
   */
  @javax.annotation.Nonnull
  public String getCollectionOwner() {
    return collectionOwner;
  }

  public void setCollectionOwner(@javax.annotation.Nonnull String collectionOwner) {
    this.collectionOwner = collectionOwner;
  }


  public CollectionListItemBody collectionScope(@javax.annotation.Nonnull String collectionScope) {
    this.collectionScope = collectionScope;
    return this;
  }

  /**
   * Get collectionScope
   * @return collectionScope
   */
  @javax.annotation.Nonnull
  public String getCollectionScope() {
    return collectionScope;
  }

  public void setCollectionScope(@javax.annotation.Nonnull String collectionScope) {
    this.collectionScope = collectionScope;
  }


  public CollectionListItemBody collectionSize(@javax.annotation.Nonnull Long collectionSize) {
    this.collectionSize = collectionSize;
    return this;
  }

  /**
   * Get collectionSize
   * @return collectionSize
   */
  @javax.annotation.Nonnull
  public Long getCollectionSize() {
    return collectionSize;
  }

  public void setCollectionSize(@javax.annotation.Nonnull Long collectionSize) {
    this.collectionSize = collectionSize;
  }


  public CollectionListItemBody collectionTags(@javax.annotation.Nullable List<String> collectionTags) {
    this.collectionTags = collectionTags;
    return this;
  }

  public CollectionListItemBody addCollectionTagsItem(String collectionTagsItem) {
    if (this.collectionTags == null) {
      this.collectionTags = new ArrayList<>();
    }
    this.collectionTags.add(collectionTagsItem);
    return this;
  }

  /**
   * Get collectionTags
   * @return collectionTags
   */
  @javax.annotation.Nullable
  public List<String> getCollectionTags() {
    return collectionTags;
  }

  public void setCollectionTags(@javax.annotation.Nullable List<String> collectionTags) {
    this.collectionTags = collectionTags;
  }


  public CollectionListItemBody creation(@javax.annotation.Nonnull OffsetDateTime creation) {
    this.creation = creation;
    return this;
  }

  /**
   * Get creation
   * @return creation
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreation() {
    return creation;
  }

  public void setCreation(@javax.annotation.Nonnull OffsetDateTime creation) {
    this.creation = creation;
  }


  public CollectionListItemBody description(@javax.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }


  public CollectionListItemBody modelName(@javax.annotation.Nonnull String modelName) {
    this.modelName = modelName;
    return this;
  }

  /**
   * Get modelName
   * @return modelName
   */
  @javax.annotation.Nonnull
  public String getModelName() {
    return modelName;
  }

  public void setModelName(@javax.annotation.Nonnull String modelName) {
    this.modelName = modelName;
  }


  public CollectionListItemBody officialCollection(@javax.annotation.Nonnull Boolean officialCollection) {
    this.officialCollection = officialCollection;
    return this;
  }

  /**
   * Get officialCollection
   * @return officialCollection
   */
  @javax.annotation.Nonnull
  public Boolean getOfficialCollection() {
    return officialCollection;
  }

  public void setOfficialCollection(@javax.annotation.Nonnull Boolean officialCollection) {
    this.officialCollection = officialCollection;
  }


  public CollectionListItemBody teamId(@javax.annotation.Nonnull Long teamId) {
    this.teamId = teamId;
    return this;
  }

  /**
   * Get teamId
   * @return teamId
   */
  @javax.annotation.Nonnull
  public Long getTeamId() {
    return teamId;
  }

  public void setTeamId(@javax.annotation.Nonnull Long teamId) {
    this.teamId = teamId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CollectionListItemBody instance itself
   */
  public CollectionListItemBody putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CollectionListItemBody collectionListItemBody = (CollectionListItemBody) o;
    return Objects.equals(this.collectionId, collectionListItemBody.collectionId) &&
        Objects.equals(this.collectionName, collectionListItemBody.collectionName) &&
        Objects.equals(this.collectionOwner, collectionListItemBody.collectionOwner) &&
        Objects.equals(this.collectionScope, collectionListItemBody.collectionScope) &&
        Objects.equals(this.collectionSize, collectionListItemBody.collectionSize) &&
        Objects.equals(this.collectionTags, collectionListItemBody.collectionTags) &&
        Objects.equals(this.creation, collectionListItemBody.creation) &&
        Objects.equals(this.description, collectionListItemBody.description) &&
        Objects.equals(this.modelName, collectionListItemBody.modelName) &&
        Objects.equals(this.officialCollection, collectionListItemBody.officialCollection) &&
        Objects.equals(this.teamId, collectionListItemBody.teamId)&&
        Objects.equals(this.additionalProperties, collectionListItemBody.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collectionId, collectionName, collectionOwner, collectionScope, collectionSize, collectionTags, creation, description, modelName, officialCollection, teamId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CollectionListItemBody {\n");
    sb.append("    collectionId: ").append(toIndentedString(collectionId)).append("\n");
    sb.append("    collectionName: ").append(toIndentedString(collectionName)).append("\n");
    sb.append("    collectionOwner: ").append(toIndentedString(collectionOwner)).append("\n");
    sb.append("    collectionScope: ").append(toIndentedString(collectionScope)).append("\n");
    sb.append("    collectionSize: ").append(toIndentedString(collectionSize)).append("\n");
    sb.append("    collectionTags: ").append(toIndentedString(collectionTags)).append("\n");
    sb.append("    creation: ").append(toIndentedString(creation)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    officialCollection: ").append(toIndentedString(officialCollection)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("collection_id", "collection_name", "collection_owner", "collection_scope", "collection_size", "collection_tags", "creation", "description", "model_name", "official_collection", "team_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("collection_id", "collection_name", "collection_owner", "collection_scope", "collection_size", "collection_tags", "creation", "description", "model_name", "official_collection", "team_id"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CollectionListItemBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CollectionListItemBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in CollectionListItemBody is not found in the empty JSON string", CollectionListItemBody.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CollectionListItemBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("collection_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `collection_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("collection_name").toString()));
      }
      if (!jsonObj.get("collection_owner").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `collection_owner` to be a primitive type in the JSON string but got `%s`", jsonObj.get("collection_owner").toString()));
      }
      if (!jsonObj.get("collection_scope").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `collection_scope` to be a primitive type in the JSON string but got `%s`", jsonObj.get("collection_scope").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("collection_tags") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("collection_tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `collection_tags` to be an array in the JSON string but got `%s`", jsonObj.get("collection_tags").toString()));
      }
      if (!jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (!jsonObj.get("model_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `model_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CollectionListItemBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CollectionListItemBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CollectionListItemBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CollectionListItemBody.class));

       return (TypeAdapter<T>) new TypeAdapter<CollectionListItemBody>() {
           @Override
           public void write(JsonWriter out, CollectionListItemBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CollectionListItemBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             CollectionListItemBody instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CollectionListItemBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CollectionListItemBody
   * @throws IOException if the JSON string is invalid with respect to CollectionListItemBody
   */
  public static CollectionListItemBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CollectionListItemBody.class);
  }

  /**
   * Convert an instance of CollectionListItemBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

