/*
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import ai.reveng.model.CopySignatureItem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.reveng.invoker.JSON;

/**
 * CopyFunctionSignaturesInputBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CopyFunctionSignaturesInputBody {
  public static final String SERIALIZED_NAME_COPIES = "copies";
  @SerializedName(SERIALIZED_NAME_COPIES)
  @javax.annotation.Nullable
  private List<CopySignatureItem> copies;

  public CopyFunctionSignaturesInputBody() {
  }

  public CopyFunctionSignaturesInputBody copies(@javax.annotation.Nullable List<CopySignatureItem> copies) {
    this.copies = copies;
    return this;
  }

  public CopyFunctionSignaturesInputBody addCopiesItem(CopySignatureItem copiesItem) {
    if (this.copies == null) {
      this.copies = new ArrayList<>();
    }
    this.copies.add(copiesItem);
    return this;
  }

  /**
   * Signatures to copy. No target may repeat, and no pair may name the same function twice.
   * @return copies
   */
  @javax.annotation.Nullable
  public List<CopySignatureItem> getCopies() {
    return copies;
  }

  public void setCopies(@javax.annotation.Nullable List<CopySignatureItem> copies) {
    this.copies = copies;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CopyFunctionSignaturesInputBody copyFunctionSignaturesInputBody = (CopyFunctionSignaturesInputBody) o;
    return Objects.equals(this.copies, copyFunctionSignaturesInputBody.copies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(copies);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CopyFunctionSignaturesInputBody {\n");
    sb.append("    copies: ").append(toIndentedString(copies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("copies"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("copies"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CopyFunctionSignaturesInputBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CopyFunctionSignaturesInputBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CopyFunctionSignaturesInputBody is not found in the empty JSON string", CopyFunctionSignaturesInputBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CopyFunctionSignaturesInputBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CopyFunctionSignaturesInputBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CopyFunctionSignaturesInputBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("copies") != null && !jsonObj.get("copies").isJsonNull()) {
        if (!jsonObj.get("copies").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `copies` to be an array in the JSON string but got `%s`", jsonObj.get("copies").toString()));
        }
        JsonArray jsonArraycopies = jsonObj.getAsJsonArray("copies");
        // validate the required field `copies` (array)
        for (int i = 0; i < jsonArraycopies.size(); i++) {
          CopySignatureItem.validateJsonElement(jsonArraycopies.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CopyFunctionSignaturesInputBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CopyFunctionSignaturesInputBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CopyFunctionSignaturesInputBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CopyFunctionSignaturesInputBody.class));

       return (TypeAdapter<T>) new TypeAdapter<CopyFunctionSignaturesInputBody>() {
           @Override
           public void write(JsonWriter out, CopyFunctionSignaturesInputBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CopyFunctionSignaturesInputBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CopyFunctionSignaturesInputBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CopyFunctionSignaturesInputBody
   * @throws IOException if the JSON string is invalid with respect to CopyFunctionSignaturesInputBody
   */
  public static CopyFunctionSignaturesInputBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CopyFunctionSignaturesInputBody.class);
  }

  /**
   * Convert an instance of CopyFunctionSignaturesInputBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

