/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.reveng.invoker.JSON;

/**
 * ELFSegment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen"", comments = "Generator version: 7.15.0")
public class ELFSegment {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public static final String SERIALIZED_NAME_VIRTUAL_ADDRESS = "virtual_address";
  @SerializedName(SERIALIZED_NAME_VIRTUAL_ADDRESS)
  @javax.annotation.Nonnull
  private Integer virtualAddress;

  public static final String SERIALIZED_NAME_VIRTUAL_SIZE = "virtual_size";
  @SerializedName(SERIALIZED_NAME_VIRTUAL_SIZE)
  @javax.annotation.Nonnull
  private Integer virtualSize;

  public static final String SERIALIZED_NAME_PHYSICAL_ADDRESS = "physical_address";
  @SerializedName(SERIALIZED_NAME_PHYSICAL_ADDRESS)
  @javax.annotation.Nonnull
  private Integer physicalAddress;

  public static final String SERIALIZED_NAME_PHYSICAL_SIZE = "physical_size";
  @SerializedName(SERIALIZED_NAME_PHYSICAL_SIZE)
  @javax.annotation.Nonnull
  private Integer physicalSize;

  public static final String SERIALIZED_NAME_FILE_OFFSET = "file_offset";
  @SerializedName(SERIALIZED_NAME_FILE_OFFSET)
  @javax.annotation.Nonnull
  private Integer fileOffset;

  public static final String SERIALIZED_NAME_FLAGS = "flags";
  @SerializedName(SERIALIZED_NAME_FLAGS)
  @javax.annotation.Nonnull
  private String flags;

  public static final String SERIALIZED_NAME_FLAGS_RAW = "flags_raw";
  @SerializedName(SERIALIZED_NAME_FLAGS_RAW)
  @javax.annotation.Nonnull
  private Integer flagsRaw;

  public static final String SERIALIZED_NAME_ALIGNMENT = "alignment";
  @SerializedName(SERIALIZED_NAME_ALIGNMENT)
  @javax.annotation.Nonnull
  private Integer alignment;

  public ELFSegment() {
  }

  public ELFSegment type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  public ELFSegment virtualAddress(@javax.annotation.Nonnull Integer virtualAddress) {
    this.virtualAddress = virtualAddress;
    return this;
  }

  /**
   * Get virtualAddress
   * @return virtualAddress
   */
  @javax.annotation.Nonnull
  public Integer getVirtualAddress() {
    return virtualAddress;
  }

  public void setVirtualAddress(@javax.annotation.Nonnull Integer virtualAddress) {
    this.virtualAddress = virtualAddress;
  }


  public ELFSegment virtualSize(@javax.annotation.Nonnull Integer virtualSize) {
    this.virtualSize = virtualSize;
    return this;
  }

  /**
   * Get virtualSize
   * @return virtualSize
   */
  @javax.annotation.Nonnull
  public Integer getVirtualSize() {
    return virtualSize;
  }

  public void setVirtualSize(@javax.annotation.Nonnull Integer virtualSize) {
    this.virtualSize = virtualSize;
  }


  public ELFSegment physicalAddress(@javax.annotation.Nonnull Integer physicalAddress) {
    this.physicalAddress = physicalAddress;
    return this;
  }

  /**
   * Get physicalAddress
   * @return physicalAddress
   */
  @javax.annotation.Nonnull
  public Integer getPhysicalAddress() {
    return physicalAddress;
  }

  public void setPhysicalAddress(@javax.annotation.Nonnull Integer physicalAddress) {
    this.physicalAddress = physicalAddress;
  }


  public ELFSegment physicalSize(@javax.annotation.Nonnull Integer physicalSize) {
    this.physicalSize = physicalSize;
    return this;
  }

  /**
   * Get physicalSize
   * @return physicalSize
   */
  @javax.annotation.Nonnull
  public Integer getPhysicalSize() {
    return physicalSize;
  }

  public void setPhysicalSize(@javax.annotation.Nonnull Integer physicalSize) {
    this.physicalSize = physicalSize;
  }


  public ELFSegment fileOffset(@javax.annotation.Nonnull Integer fileOffset) {
    this.fileOffset = fileOffset;
    return this;
  }

  /**
   * Get fileOffset
   * @return fileOffset
   */
  @javax.annotation.Nonnull
  public Integer getFileOffset() {
    return fileOffset;
  }

  public void setFileOffset(@javax.annotation.Nonnull Integer fileOffset) {
    this.fileOffset = fileOffset;
  }


  public ELFSegment flags(@javax.annotation.Nonnull String flags) {
    this.flags = flags;
    return this;
  }

  /**
   * Get flags
   * @return flags
   */
  @javax.annotation.Nonnull
  public String getFlags() {
    return flags;
  }

  public void setFlags(@javax.annotation.Nonnull String flags) {
    this.flags = flags;
  }


  public ELFSegment flagsRaw(@javax.annotation.Nonnull Integer flagsRaw) {
    this.flagsRaw = flagsRaw;
    return this;
  }

  /**
   * Get flagsRaw
   * @return flagsRaw
   */
  @javax.annotation.Nonnull
  public Integer getFlagsRaw() {
    return flagsRaw;
  }

  public void setFlagsRaw(@javax.annotation.Nonnull Integer flagsRaw) {
    this.flagsRaw = flagsRaw;
  }


  public ELFSegment alignment(@javax.annotation.Nonnull Integer alignment) {
    this.alignment = alignment;
    return this;
  }

  /**
   * Get alignment
   * @return alignment
   */
  @javax.annotation.Nonnull
  public Integer getAlignment() {
    return alignment;
  }

  public void setAlignment(@javax.annotation.Nonnull Integer alignment) {
    this.alignment = alignment;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ELFSegment elFSegment = (ELFSegment) o;
    return Objects.equals(this.type, elFSegment.type) &&
        Objects.equals(this.virtualAddress, elFSegment.virtualAddress) &&
        Objects.equals(this.virtualSize, elFSegment.virtualSize) &&
        Objects.equals(this.physicalAddress, elFSegment.physicalAddress) &&
        Objects.equals(this.physicalSize, elFSegment.physicalSize) &&
        Objects.equals(this.fileOffset, elFSegment.fileOffset) &&
        Objects.equals(this.flags, elFSegment.flags) &&
        Objects.equals(this.flagsRaw, elFSegment.flagsRaw) &&
        Objects.equals(this.alignment, elFSegment.alignment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, virtualAddress, virtualSize, physicalAddress, physicalSize, fileOffset, flags, flagsRaw, alignment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ELFSegment {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    virtualAddress: ").append(toIndentedString(virtualAddress)).append("\n");
    sb.append("    virtualSize: ").append(toIndentedString(virtualSize)).append("\n");
    sb.append("    physicalAddress: ").append(toIndentedString(physicalAddress)).append("\n");
    sb.append("    physicalSize: ").append(toIndentedString(physicalSize)).append("\n");
    sb.append("    fileOffset: ").append(toIndentedString(fileOffset)).append("\n");
    sb.append("    flags: ").append(toIndentedString(flags)).append("\n");
    sb.append("    flagsRaw: ").append(toIndentedString(flagsRaw)).append("\n");
    sb.append("    alignment: ").append(toIndentedString(alignment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "virtual_address", "virtual_size", "physical_address", "physical_size", "file_offset", "flags", "flags_raw", "alignment"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "virtual_address", "virtual_size", "physical_address", "physical_size", "file_offset", "flags", "flags_raw", "alignment"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ELFSegment
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ELFSegment.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ELFSegment is not found in the empty JSON string", ELFSegment.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ELFSegment.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ELFSegment` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ELFSegment.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if (!jsonObj.get("flags").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `flags` to be a primitive type in the JSON string but got `%s`", jsonObj.get("flags").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ELFSegment.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ELFSegment' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ELFSegment> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ELFSegment.class));

       return (TypeAdapter<T>) new TypeAdapter<ELFSegment>() {
           @Override
           public void write(JsonWriter out, ELFSegment value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ELFSegment read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ELFSegment given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ELFSegment
   * @throws IOException if the JSON string is invalid with respect to ELFSegment
   */
  public static ELFSegment fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ELFSegment.class);
  }

  /**
   * Convert an instance of ELFSegment to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

