/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * The version of the OpenAPI document: v1.92.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.reveng.invoker.JSON;

/**
 * FileHashes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-25T21:28:50.782706+01:00[Europe/London]", comments = "Generator version: 7.15.0")
public class FileHashes {
  public static final String SERIALIZED_NAME_MD5 = "md5";
  @SerializedName(SERIALIZED_NAME_MD5)
  @javax.annotation.Nullable
  private String md5;

  public static final String SERIALIZED_NAME_SHA1 = "sha1";
  @SerializedName(SERIALIZED_NAME_SHA1)
  @javax.annotation.Nullable
  private String sha1;

  public static final String SERIALIZED_NAME_SHA256 = "sha256";
  @SerializedName(SERIALIZED_NAME_SHA256)
  @javax.annotation.Nullable
  private String sha256;

  public static final String SERIALIZED_NAME_SHA512 = "sha512";
  @SerializedName(SERIALIZED_NAME_SHA512)
  @javax.annotation.Nullable
  private String sha512;

  public static final String SERIALIZED_NAME_SHA3224 = "sha3_224";
  @SerializedName(SERIALIZED_NAME_SHA3224)
  @javax.annotation.Nullable
  private String sha3224;

  public static final String SERIALIZED_NAME_SHA3256 = "sha3_256";
  @SerializedName(SERIALIZED_NAME_SHA3256)
  @javax.annotation.Nullable
  private String sha3256;

  public static final String SERIALIZED_NAME_SHA3384 = "sha3_384";
  @SerializedName(SERIALIZED_NAME_SHA3384)
  @javax.annotation.Nullable
  private String sha3384;

  public static final String SERIALIZED_NAME_SHA3512 = "sha3_512";
  @SerializedName(SERIALIZED_NAME_SHA3512)
  @javax.annotation.Nullable
  private String sha3512;

  public FileHashes() {
  }

  public FileHashes md5(@javax.annotation.Nullable String md5) {
    this.md5 = md5;
    return this;
  }

  /**
   * Get md5
   * @return md5
   */
  @javax.annotation.Nullable
  public String getMd5() {
    return md5;
  }

  public void setMd5(@javax.annotation.Nullable String md5) {
    this.md5 = md5;
  }


  public FileHashes sha1(@javax.annotation.Nullable String sha1) {
    this.sha1 = sha1;
    return this;
  }

  /**
   * Get sha1
   * @return sha1
   */
  @javax.annotation.Nullable
  public String getSha1() {
    return sha1;
  }

  public void setSha1(@javax.annotation.Nullable String sha1) {
    this.sha1 = sha1;
  }


  public FileHashes sha256(@javax.annotation.Nullable String sha256) {
    this.sha256 = sha256;
    return this;
  }

  /**
   * Get sha256
   * @return sha256
   */
  @javax.annotation.Nullable
  public String getSha256() {
    return sha256;
  }

  public void setSha256(@javax.annotation.Nullable String sha256) {
    this.sha256 = sha256;
  }


  public FileHashes sha512(@javax.annotation.Nullable String sha512) {
    this.sha512 = sha512;
    return this;
  }

  /**
   * Get sha512
   * @return sha512
   */
  @javax.annotation.Nullable
  public String getSha512() {
    return sha512;
  }

  public void setSha512(@javax.annotation.Nullable String sha512) {
    this.sha512 = sha512;
  }


  public FileHashes sha3224(@javax.annotation.Nullable String sha3224) {
    this.sha3224 = sha3224;
    return this;
  }

  /**
   * Get sha3224
   * @return sha3224
   */
  @javax.annotation.Nullable
  public String getSha3224() {
    return sha3224;
  }

  public void setSha3224(@javax.annotation.Nullable String sha3224) {
    this.sha3224 = sha3224;
  }


  public FileHashes sha3256(@javax.annotation.Nullable String sha3256) {
    this.sha3256 = sha3256;
    return this;
  }

  /**
   * Get sha3256
   * @return sha3256
   */
  @javax.annotation.Nullable
  public String getSha3256() {
    return sha3256;
  }

  public void setSha3256(@javax.annotation.Nullable String sha3256) {
    this.sha3256 = sha3256;
  }


  public FileHashes sha3384(@javax.annotation.Nullable String sha3384) {
    this.sha3384 = sha3384;
    return this;
  }

  /**
   * Get sha3384
   * @return sha3384
   */
  @javax.annotation.Nullable
  public String getSha3384() {
    return sha3384;
  }

  public void setSha3384(@javax.annotation.Nullable String sha3384) {
    this.sha3384 = sha3384;
  }


  public FileHashes sha3512(@javax.annotation.Nullable String sha3512) {
    this.sha3512 = sha3512;
    return this;
  }

  /**
   * Get sha3512
   * @return sha3512
   */
  @javax.annotation.Nullable
  public String getSha3512() {
    return sha3512;
  }

  public void setSha3512(@javax.annotation.Nullable String sha3512) {
    this.sha3512 = sha3512;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileHashes fileHashes = (FileHashes) o;
    return Objects.equals(this.md5, fileHashes.md5) &&
        Objects.equals(this.sha1, fileHashes.sha1) &&
        Objects.equals(this.sha256, fileHashes.sha256) &&
        Objects.equals(this.sha512, fileHashes.sha512) &&
        Objects.equals(this.sha3224, fileHashes.sha3224) &&
        Objects.equals(this.sha3256, fileHashes.sha3256) &&
        Objects.equals(this.sha3384, fileHashes.sha3384) &&
        Objects.equals(this.sha3512, fileHashes.sha3512);
  }

  @Override
  public int hashCode() {
    return Objects.hash(md5, sha1, sha256, sha512, sha3224, sha3256, sha3384, sha3512);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileHashes {\n");
    sb.append("    md5: ").append(toIndentedString(md5)).append("\n");
    sb.append("    sha1: ").append(toIndentedString(sha1)).append("\n");
    sb.append("    sha256: ").append(toIndentedString(sha256)).append("\n");
    sb.append("    sha512: ").append(toIndentedString(sha512)).append("\n");
    sb.append("    sha3224: ").append(toIndentedString(sha3224)).append("\n");
    sb.append("    sha3256: ").append(toIndentedString(sha3256)).append("\n");
    sb.append("    sha3384: ").append(toIndentedString(sha3384)).append("\n");
    sb.append("    sha3512: ").append(toIndentedString(sha3512)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("md5", "sha1", "sha256", "sha512", "sha3_224", "sha3_256", "sha3_384", "sha3_512"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("md5", "sha1", "sha256", "sha512", "sha3_224", "sha3_256", "sha3_384", "sha3_512"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FileHashes
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FileHashes.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FileHashes is not found in the empty JSON string", FileHashes.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FileHashes.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FileHashes` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FileHashes.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("md5") != null && !jsonObj.get("md5").isJsonNull()) && !jsonObj.get("md5").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `md5` to be a primitive type in the JSON string but got `%s`", jsonObj.get("md5").toString()));
      }
      if ((jsonObj.get("sha1") != null && !jsonObj.get("sha1").isJsonNull()) && !jsonObj.get("sha1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sha1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sha1").toString()));
      }
      if ((jsonObj.get("sha256") != null && !jsonObj.get("sha256").isJsonNull()) && !jsonObj.get("sha256").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sha256` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sha256").toString()));
      }
      if ((jsonObj.get("sha512") != null && !jsonObj.get("sha512").isJsonNull()) && !jsonObj.get("sha512").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sha512` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sha512").toString()));
      }
      if ((jsonObj.get("sha3_224") != null && !jsonObj.get("sha3_224").isJsonNull()) && !jsonObj.get("sha3_224").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sha3_224` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sha3_224").toString()));
      }
      if ((jsonObj.get("sha3_256") != null && !jsonObj.get("sha3_256").isJsonNull()) && !jsonObj.get("sha3_256").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sha3_256` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sha3_256").toString()));
      }
      if ((jsonObj.get("sha3_384") != null && !jsonObj.get("sha3_384").isJsonNull()) && !jsonObj.get("sha3_384").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sha3_384` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sha3_384").toString()));
      }
      if ((jsonObj.get("sha3_512") != null && !jsonObj.get("sha3_512").isJsonNull()) && !jsonObj.get("sha3_512").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sha3_512` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sha3_512").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FileHashes.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FileHashes' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FileHashes> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FileHashes.class));

       return (TypeAdapter<T>) new TypeAdapter<FileHashes>() {
           @Override
           public void write(JsonWriter out, FileHashes value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FileHashes read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FileHashes given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FileHashes
   * @throws IOException if the JSON string is invalid with respect to FileHashes
   */
  public static FileHashes fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FileHashes.class);
  }

  /**
   * Convert an instance of FileHashes to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

