/*
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.reveng.invoker.JSON;

/**
 * FunctionsProgressOutputBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FunctionsProgressOutputBody {
  public static final String SERIALIZED_NAME_FUNCTION_EMBEDDINGS_COUNT = "function_embeddings_count";
  @SerializedName(SERIALIZED_NAME_FUNCTION_EMBEDDINGS_COUNT)
  @javax.annotation.Nonnull
  private Long functionEmbeddingsCount;

  public static final String SERIALIZED_NAME_FUNCTIONS_COUNT = "functions_count";
  @SerializedName(SERIALIZED_NAME_FUNCTIONS_COUNT)
  @javax.annotation.Nonnull
  private Long functionsCount;

  public static final String SERIALIZED_NAME_PERCENTAGE_COMPLETED = "percentage_completed";
  @SerializedName(SERIALIZED_NAME_PERCENTAGE_COMPLETED)
  @javax.annotation.Nonnull
  private Double percentageCompleted;

  public FunctionsProgressOutputBody() {
  }

  public FunctionsProgressOutputBody functionEmbeddingsCount(@javax.annotation.Nonnull Long functionEmbeddingsCount) {
    this.functionEmbeddingsCount = functionEmbeddingsCount;
    return this;
  }

  /**
   * Functions whose embedding has been written back
   * @return functionEmbeddingsCount
   */
  @javax.annotation.Nonnull
  public Long getFunctionEmbeddingsCount() {
    return functionEmbeddingsCount;
  }

  public void setFunctionEmbeddingsCount(@javax.annotation.Nonnull Long functionEmbeddingsCount) {
    this.functionEmbeddingsCount = functionEmbeddingsCount;
  }


  public FunctionsProgressOutputBody functionsCount(@javax.annotation.Nonnull Long functionsCount) {
    this.functionsCount = functionsCount;
    return this;
  }

  /**
   * Functions found in the analysis
   * @return functionsCount
   */
  @javax.annotation.Nonnull
  public Long getFunctionsCount() {
    return functionsCount;
  }

  public void setFunctionsCount(@javax.annotation.Nonnull Long functionsCount) {
    this.functionsCount = functionsCount;
  }


  public FunctionsProgressOutputBody percentageCompleted(@javax.annotation.Nonnull Double percentageCompleted) {
    this.percentageCompleted = percentageCompleted;
    return this;
  }

  /**
   * Embeddings as a percentage of functions, to 2 decimal places. 0 when the analysis has no functions
   * @return percentageCompleted
   */
  @javax.annotation.Nonnull
  public Double getPercentageCompleted() {
    return percentageCompleted;
  }

  public void setPercentageCompleted(@javax.annotation.Nonnull Double percentageCompleted) {
    this.percentageCompleted = percentageCompleted;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the FunctionsProgressOutputBody instance itself
   */
  public FunctionsProgressOutputBody putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FunctionsProgressOutputBody functionsProgressOutputBody = (FunctionsProgressOutputBody) o;
    return Objects.equals(this.functionEmbeddingsCount, functionsProgressOutputBody.functionEmbeddingsCount) &&
        Objects.equals(this.functionsCount, functionsProgressOutputBody.functionsCount) &&
        Objects.equals(this.percentageCompleted, functionsProgressOutputBody.percentageCompleted)&&
        Objects.equals(this.additionalProperties, functionsProgressOutputBody.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(functionEmbeddingsCount, functionsCount, percentageCompleted, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FunctionsProgressOutputBody {\n");
    sb.append("    functionEmbeddingsCount: ").append(toIndentedString(functionEmbeddingsCount)).append("\n");
    sb.append("    functionsCount: ").append(toIndentedString(functionsCount)).append("\n");
    sb.append("    percentageCompleted: ").append(toIndentedString(percentageCompleted)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("function_embeddings_count", "functions_count", "percentage_completed"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("function_embeddings_count", "functions_count", "percentage_completed"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FunctionsProgressOutputBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FunctionsProgressOutputBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in FunctionsProgressOutputBody is not found in the empty JSON string", FunctionsProgressOutputBody.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FunctionsProgressOutputBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FunctionsProgressOutputBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FunctionsProgressOutputBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FunctionsProgressOutputBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FunctionsProgressOutputBody.class));

       return (TypeAdapter<T>) new TypeAdapter<FunctionsProgressOutputBody>() {
           @Override
           public void write(JsonWriter out, FunctionsProgressOutputBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public FunctionsProgressOutputBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             FunctionsProgressOutputBody instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FunctionsProgressOutputBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FunctionsProgressOutputBody
   * @throws IOException if the JSON string is invalid with respect to FunctionsProgressOutputBody
   */
  public static FunctionsProgressOutputBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FunctionsProgressOutputBody.class);
  }

  /**
   * Convert an instance of FunctionsProgressOutputBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

