/*
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import ai.reveng.model.FunctionStringItem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.reveng.invoker.JSON;

/**
 * ListFunctionStringsOutputBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ListFunctionStringsOutputBody {
  public static final String SERIALIZED_NAME_STRINGS = "strings";
  @SerializedName(SERIALIZED_NAME_STRINGS)
  @javax.annotation.Nullable
  private List<FunctionStringItem> strings;

  public static final String SERIALIZED_NAME_TOTAL_STRINGS = "total_strings";
  @SerializedName(SERIALIZED_NAME_TOTAL_STRINGS)
  @javax.annotation.Nonnull
  private Long totalStrings;

  public ListFunctionStringsOutputBody() {
  }

  public ListFunctionStringsOutputBody strings(@javax.annotation.Nullable List<FunctionStringItem> strings) {
    this.strings = strings;
    return this;
  }

  public ListFunctionStringsOutputBody addStringsItem(FunctionStringItem stringsItem) {
    if (this.strings == null) {
      this.strings = new ArrayList<>();
    }
    this.strings.add(stringsItem);
    return this;
  }

  /**
   * Get strings
   * @return strings
   */
  @javax.annotation.Nullable
  public List<FunctionStringItem> getStrings() {
    return strings;
  }

  public void setStrings(@javax.annotation.Nullable List<FunctionStringItem> strings) {
    this.strings = strings;
  }


  public ListFunctionStringsOutputBody totalStrings(@javax.annotation.Nonnull Long totalStrings) {
    this.totalStrings = totalStrings;
    return this;
  }

  /**
   * Get totalStrings
   * @return totalStrings
   */
  @javax.annotation.Nonnull
  public Long getTotalStrings() {
    return totalStrings;
  }

  public void setTotalStrings(@javax.annotation.Nonnull Long totalStrings) {
    this.totalStrings = totalStrings;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListFunctionStringsOutputBody listFunctionStringsOutputBody = (ListFunctionStringsOutputBody) o;
    return Objects.equals(this.strings, listFunctionStringsOutputBody.strings) &&
        Objects.equals(this.totalStrings, listFunctionStringsOutputBody.totalStrings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(strings, totalStrings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListFunctionStringsOutputBody {\n");
    sb.append("    strings: ").append(toIndentedString(strings)).append("\n");
    sb.append("    totalStrings: ").append(toIndentedString(totalStrings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("strings", "total_strings"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("strings", "total_strings"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListFunctionStringsOutputBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListFunctionStringsOutputBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ListFunctionStringsOutputBody is not found in the empty JSON string", ListFunctionStringsOutputBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListFunctionStringsOutputBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ListFunctionStringsOutputBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ListFunctionStringsOutputBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("strings") != null && !jsonObj.get("strings").isJsonNull()) {
        if (!jsonObj.get("strings").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `strings` to be an array in the JSON string but got `%s`", jsonObj.get("strings").toString()));
        }
        JsonArray jsonArraystrings = jsonObj.getAsJsonArray("strings");
        // validate the required field `strings` (array)
        for (int i = 0; i < jsonArraystrings.size(); i++) {
          FunctionStringItem.validateJsonElement(jsonArraystrings.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListFunctionStringsOutputBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListFunctionStringsOutputBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListFunctionStringsOutputBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListFunctionStringsOutputBody.class));

       return (TypeAdapter<T>) new TypeAdapter<ListFunctionStringsOutputBody>() {
           @Override
           public void write(JsonWriter out, ListFunctionStringsOutputBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListFunctionStringsOutputBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListFunctionStringsOutputBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListFunctionStringsOutputBody
   * @throws IOException if the JSON string is invalid with respect to ListFunctionStringsOutputBody
   */
  public static ListFunctionStringsOutputBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListFunctionStringsOutputBody.class);
  }

  /**
   * Convert an instance of ListFunctionStringsOutputBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

