/*
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Custom enum for the model name
 */
@JsonAdapter(ModelName.Adapter.class)
public enum ModelName {
  
  BINNET_0_7_X86_64_WINDOWS("binnet-0.7-x86-64-windows"),
  
  BINNET_0_7_X86_64_LINUX("binnet-0.7-x86-64-linux"),
  
  BINNET_0_7_X86_32_WINDOWS("binnet-0.7-x86-32-windows"),
  
  BINNET_0_7_X86_32_LINUX("binnet-0.7-x86-32-linux"),
  
  BINNET_0_7_ARM_64_WINDOWS("binnet-0.7-arm-64-windows"),
  
  BINNET_0_7_ARM_64_LINUX("binnet-0.7-arm-64-linux"),
  
  BINNET_0_7_X86_64_ANDROID("binnet-0.7-x86-64-android"),
  
  BINNET_0_7_X86_32_ANDROID("binnet-0.7-x86-32-android"),
  
  BINNET_0_7_ARM_64_ANDROID("binnet-0.7-arm-64-android"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  ModelName(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ModelName fromValue(String value) {
    for (ModelName b : ModelName.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<ModelName> {
    @Override
    public void write(final JsonWriter jsonWriter, final ModelName enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ModelName read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ModelName.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ModelName.fromValue(value);
  }
}

