/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * The version of the OpenAPI document: v1.92.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets SeverityType
 */
@JsonAdapter(SeverityType.Adapter.class)
public enum SeverityType {
  
  CRITICAL("CRITICAL"),
  
  HIGH("HIGH"),
  
  MEDIUM("MEDIUM"),
  
  LOW("LOW"),
  
  INFO("INFO"),
  
  NONE("NONE");

  private String value;

  SeverityType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SeverityType fromValue(String value) {
    for (SeverityType b : SeverityType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SeverityType> {
    @Override
    public void write(final JsonWriter jsonWriter, final SeverityType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SeverityType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SeverityType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    SeverityType.fromValue(value);
  }
}

