/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.model;

import java.util.Objects;
import java.util.Locale;
import ai.reveng.model.FunctionInfoInput;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import ai.reveng.invoker.JSON;

/**
 * UpdateFunctionDataTypes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdateFunctionDataTypes {
  public static final String SERIALIZED_NAME_DATA_TYPES_VERSION = "data_types_version";
  @SerializedName(SERIALIZED_NAME_DATA_TYPES_VERSION)
  @javax.annotation.Nonnull
  private Integer dataTypesVersion;

  public static final String SERIALIZED_NAME_DATA_TYPES = "data_types";
  @SerializedName(SERIALIZED_NAME_DATA_TYPES)
  @javax.annotation.Nonnull
  private FunctionInfoInput dataTypes;

  public UpdateFunctionDataTypes() {
  }

  public UpdateFunctionDataTypes dataTypesVersion(@javax.annotation.Nonnull Integer dataTypesVersion) {
    this.dataTypesVersion = dataTypesVersion;
    return this;
  }

  /**
   * Version of the function data types, used to check this update is not overwriting a newer one
   * @return dataTypesVersion
   */
  @javax.annotation.Nonnull
  public Integer getDataTypesVersion() {
    return dataTypesVersion;
  }

  public void setDataTypesVersion(@javax.annotation.Nonnull Integer dataTypesVersion) {
    this.dataTypesVersion = dataTypesVersion;
  }


  public UpdateFunctionDataTypes dataTypes(@javax.annotation.Nonnull FunctionInfoInput dataTypes) {
    this.dataTypes = dataTypes;
    return this;
  }

  /**
   * Function data types information to update
   * @return dataTypes
   */
  @javax.annotation.Nonnull
  public FunctionInfoInput getDataTypes() {
    return dataTypes;
  }

  public void setDataTypes(@javax.annotation.Nonnull FunctionInfoInput dataTypes) {
    this.dataTypes = dataTypes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateFunctionDataTypes updateFunctionDataTypes = (UpdateFunctionDataTypes) o;
    return Objects.equals(this.dataTypesVersion, updateFunctionDataTypes.dataTypesVersion) &&
        Objects.equals(this.dataTypes, updateFunctionDataTypes.dataTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataTypesVersion, dataTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateFunctionDataTypes {\n");
    sb.append("    dataTypesVersion: ").append(toIndentedString(dataTypesVersion)).append("\n");
    sb.append("    dataTypes: ").append(toIndentedString(dataTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("data_types_version", "data_types"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("data_types_version", "data_types"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateFunctionDataTypes
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateFunctionDataTypes.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in UpdateFunctionDataTypes is not found in the empty JSON string", UpdateFunctionDataTypes.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateFunctionDataTypes.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UpdateFunctionDataTypes` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdateFunctionDataTypes.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `data_types`
      FunctionInfoInput.validateJsonElement(jsonObj.get("data_types"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateFunctionDataTypes.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateFunctionDataTypes' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateFunctionDataTypes> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateFunctionDataTypes.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateFunctionDataTypes>() {
           @Override
           public void write(JsonWriter out, UpdateFunctionDataTypes value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateFunctionDataTypes read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateFunctionDataTypes given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateFunctionDataTypes
   * @throws IOException if the JSON string is invalid with respect to UpdateFunctionDataTypes
   */
  public static UpdateFunctionDataTypes fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateFunctionDataTypes.class);
  }

  /**
   * Convert an instance of UpdateFunctionDataTypes to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

