/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.api;

import ai.reveng.invoker.ApiCallback;
import ai.reveng.invoker.ApiClient;
import ai.reveng.invoker.ApiException;
import ai.reveng.invoker.ApiResponse;
import ai.reveng.invoker.Configuration;
import ai.reveng.invoker.Pair;
import ai.reveng.invoker.ProgressRequestBody;
import ai.reveng.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.reveng.model.BaseResponse;
import ai.reveng.model.BaseResponseAnalysisFunctions;
import ai.reveng.model.BaseResponseAnalysisTags;
import ai.reveng.model.BaseResponseCapabilities;
import ai.reveng.model.BaseResponseCommunities;
import ai.reveng.model.BaseResponseListSBOM;
import ai.reveng.model.BaseResponseVulnerabilities;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AnalysesResultsMetadataApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AnalysesResultsMetadataApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AnalysesResultsMetadataApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getCapabilities
     * @param analysisId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCapabilitiesCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/capabilities"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCapabilitiesValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling getCapabilities(Async)");
        }

        return getCapabilitiesCall(analysisId, _callback);

    }

    /**
     * Gets the capabilities from the analysis
     * 
     * @param analysisId  (required)
     * @return BaseResponseCapabilities
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseCapabilities getCapabilities(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        ApiResponse<BaseResponseCapabilities> localVarResp = getCapabilitiesWithHttpInfo(analysisId);
        return localVarResp.getData();
    }

    /**
     * Gets the capabilities from the analysis
     * 
     * @param analysisId  (required)
     * @return ApiResponse&lt;BaseResponseCapabilities&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseCapabilities> getCapabilitiesWithHttpInfo(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        okhttp3.Call localVarCall = getCapabilitiesValidateBeforeCall(analysisId, null);
        Type localVarReturnType = new TypeToken<BaseResponseCapabilities>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Gets the capabilities from the analysis (asynchronously)
     * 
     * @param analysisId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCapabilitiesAsync(@javax.annotation.Nonnull Integer analysisId, final ApiCallback<BaseResponseCapabilities> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCapabilitiesValidateBeforeCall(analysisId, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseCapabilities>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getCommunities
     * @param analysisId  (required)
     * @param userName The user name to limit communities to (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCommunitiesCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable String userName, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/communities"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (userName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("user_name", userName));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCommunitiesValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable String userName, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling getCommunities(Async)");
        }

        return getCommunitiesCall(analysisId, userName, _callback);

    }

    /**
     * Gets the communities found in the analysis
     * 
     * @param analysisId  (required)
     * @param userName The user name to limit communities to (optional)
     * @return BaseResponseCommunities
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseCommunities getCommunities(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable String userName) throws ApiException {
        ApiResponse<BaseResponseCommunities> localVarResp = getCommunitiesWithHttpInfo(analysisId, userName);
        return localVarResp.getData();
    }

    /**
     * Gets the communities found in the analysis
     * 
     * @param analysisId  (required)
     * @param userName The user name to limit communities to (optional)
     * @return ApiResponse&lt;BaseResponseCommunities&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseCommunities> getCommunitiesWithHttpInfo(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable String userName) throws ApiException {
        okhttp3.Call localVarCall = getCommunitiesValidateBeforeCall(analysisId, userName, null);
        Type localVarReturnType = new TypeToken<BaseResponseCommunities>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Gets the communities found in the analysis (asynchronously)
     * 
     * @param analysisId  (required)
     * @param userName The user name to limit communities to (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCommunitiesAsync(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable String userName, final ApiCallback<BaseResponseCommunities> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCommunitiesValidateBeforeCall(analysisId, userName, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseCommunities>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getFunctionsList
     * @param analysisId  (required)
     * @param searchTerm  (optional)
     * @param minVAddr  (optional)
     * @param maxVAddr  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionsListCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable String searchTerm, @javax.annotation.Nullable Integer minVAddr, @javax.annotation.Nullable Integer maxVAddr, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/functions/list"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (searchTerm != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("search_term", searchTerm));
        }

        if (minVAddr != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("min_v_addr", minVAddr));
        }

        if (maxVAddr != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("max_v_addr", maxVAddr));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getFunctionsListValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable String searchTerm, @javax.annotation.Nullable Integer minVAddr, @javax.annotation.Nullable Integer maxVAddr, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling getFunctionsList(Async)");
        }

        return getFunctionsListCall(analysisId, searchTerm, minVAddr, maxVAddr, _callback);

    }

    /**
     * Gets functions from analysis
     * Gets the functions identified during analysis
     * @param analysisId  (required)
     * @param searchTerm  (optional)
     * @param minVAddr  (optional)
     * @param maxVAddr  (optional)
     * @return BaseResponseAnalysisFunctions
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseAnalysisFunctions getFunctionsList(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable String searchTerm, @javax.annotation.Nullable Integer minVAddr, @javax.annotation.Nullable Integer maxVAddr) throws ApiException {
        ApiResponse<BaseResponseAnalysisFunctions> localVarResp = getFunctionsListWithHttpInfo(analysisId, searchTerm, minVAddr, maxVAddr);
        return localVarResp.getData();
    }

    /**
     * Gets functions from analysis
     * Gets the functions identified during analysis
     * @param analysisId  (required)
     * @param searchTerm  (optional)
     * @param minVAddr  (optional)
     * @param maxVAddr  (optional)
     * @return ApiResponse&lt;BaseResponseAnalysisFunctions&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseAnalysisFunctions> getFunctionsListWithHttpInfo(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable String searchTerm, @javax.annotation.Nullable Integer minVAddr, @javax.annotation.Nullable Integer maxVAddr) throws ApiException {
        okhttp3.Call localVarCall = getFunctionsListValidateBeforeCall(analysisId, searchTerm, minVAddr, maxVAddr, null);
        Type localVarReturnType = new TypeToken<BaseResponseAnalysisFunctions>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Gets functions from analysis (asynchronously)
     * Gets the functions identified during analysis
     * @param analysisId  (required)
     * @param searchTerm  (optional)
     * @param minVAddr  (optional)
     * @param maxVAddr  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionsListAsync(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable String searchTerm, @javax.annotation.Nullable Integer minVAddr, @javax.annotation.Nullable Integer maxVAddr, final ApiCallback<BaseResponseAnalysisFunctions> _callback) throws ApiException {

        okhttp3.Call localVarCall = getFunctionsListValidateBeforeCall(analysisId, searchTerm, minVAddr, maxVAddr, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseAnalysisFunctions>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getPdf
     * @param analysisId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPdfCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/pdf"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPdfValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling getPdf(Async)");
        }

        return getPdfCall(analysisId, _callback);

    }

    /**
     * Gets the PDF found in the analysis
     * 
     * @param analysisId  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public Object getPdf(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        ApiResponse<Object> localVarResp = getPdfWithHttpInfo(analysisId);
        return localVarResp.getData();
    }

    /**
     * Gets the PDF found in the analysis
     * 
     * @param analysisId  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> getPdfWithHttpInfo(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        okhttp3.Call localVarCall = getPdfValidateBeforeCall(analysisId, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Gets the PDF found in the analysis (asynchronously)
     * 
     * @param analysisId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPdfAsync(@javax.annotation.Nonnull Integer analysisId, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPdfValidateBeforeCall(analysisId, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getSbom
     * @param analysisId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSbomCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/sbom"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSbomValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling getSbom(Async)");
        }

        return getSbomCall(analysisId, _callback);

    }

    /**
     * Gets the software-bill-of-materials (SBOM) found in the analysis
     * 
     * @param analysisId  (required)
     * @return BaseResponseListSBOM
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseListSBOM getSbom(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        ApiResponse<BaseResponseListSBOM> localVarResp = getSbomWithHttpInfo(analysisId);
        return localVarResp.getData();
    }

    /**
     * Gets the software-bill-of-materials (SBOM) found in the analysis
     * 
     * @param analysisId  (required)
     * @return ApiResponse&lt;BaseResponseListSBOM&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseListSBOM> getSbomWithHttpInfo(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        okhttp3.Call localVarCall = getSbomValidateBeforeCall(analysisId, null);
        Type localVarReturnType = new TypeToken<BaseResponseListSBOM>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Gets the software-bill-of-materials (SBOM) found in the analysis (asynchronously)
     * 
     * @param analysisId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSbomAsync(@javax.annotation.Nonnull Integer analysisId, final ApiCallback<BaseResponseListSBOM> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSbomValidateBeforeCall(analysisId, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseListSBOM>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getTags
     * @param analysisId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTagsCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/tags"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTagsValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling getTags(Async)");
        }

        return getTagsCall(analysisId, _callback);

    }

    /**
     * Get function tags with maliciousness score
     * 
     * @param analysisId  (required)
     * @return BaseResponseAnalysisTags
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseAnalysisTags getTags(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        ApiResponse<BaseResponseAnalysisTags> localVarResp = getTagsWithHttpInfo(analysisId);
        return localVarResp.getData();
    }

    /**
     * Get function tags with maliciousness score
     * 
     * @param analysisId  (required)
     * @return ApiResponse&lt;BaseResponseAnalysisTags&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseAnalysisTags> getTagsWithHttpInfo(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        okhttp3.Call localVarCall = getTagsValidateBeforeCall(analysisId, null);
        Type localVarReturnType = new TypeToken<BaseResponseAnalysisTags>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get function tags with maliciousness score (asynchronously)
     * 
     * @param analysisId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTagsAsync(@javax.annotation.Nonnull Integer analysisId, final ApiCallback<BaseResponseAnalysisTags> _callback) throws ApiException {

        okhttp3.Call localVarCall = getTagsValidateBeforeCall(analysisId, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseAnalysisTags>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getVulnerabilities
     * @param analysisId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getVulnerabilitiesCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/vulnerabilities"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getVulnerabilitiesValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling getVulnerabilities(Async)");
        }

        return getVulnerabilitiesCall(analysisId, _callback);

    }

    /**
     * Gets the vulnerabilities found in the analysis
     * 
     * @param analysisId  (required)
     * @return BaseResponseVulnerabilities
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseVulnerabilities getVulnerabilities(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        ApiResponse<BaseResponseVulnerabilities> localVarResp = getVulnerabilitiesWithHttpInfo(analysisId);
        return localVarResp.getData();
    }

    /**
     * Gets the vulnerabilities found in the analysis
     * 
     * @param analysisId  (required)
     * @return ApiResponse&lt;BaseResponseVulnerabilities&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseVulnerabilities> getVulnerabilitiesWithHttpInfo(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        okhttp3.Call localVarCall = getVulnerabilitiesValidateBeforeCall(analysisId, null);
        Type localVarReturnType = new TypeToken<BaseResponseVulnerabilities>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Gets the vulnerabilities found in the analysis (asynchronously)
     * 
     * @param analysisId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getVulnerabilitiesAsync(@javax.annotation.Nonnull Integer analysisId, final ApiCallback<BaseResponseVulnerabilities> _callback) throws ApiException {

        okhttp3.Call localVarCall = getVulnerabilitiesValidateBeforeCall(analysisId, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseVulnerabilities>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
