/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * The version of the OpenAPI document: v1.92.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.api;

import ai.reveng.invoker.ApiCallback;
import ai.reveng.invoker.ApiClient;
import ai.reveng.invoker.ApiException;
import ai.reveng.invoker.ApiResponse;
import ai.reveng.invoker.Configuration;
import ai.reveng.invoker.Pair;
import ai.reveng.invoker.ProgressRequestBody;
import ai.reveng.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.reveng.model.BaseResponse;
import ai.reveng.model.BaseResponseBool;
import ai.reveng.model.BaseResponseCommentResponse;
import ai.reveng.model.BaseResponseDecompilationResponse;
import ai.reveng.model.BaseResponseFunctionTaskResponse;
import ai.reveng.model.BaseResponseListCommentResponse;
import ai.reveng.model.BaseResponseStr;
import ai.reveng.model.CommentUpdateRequest;
import ai.reveng.model.FunctionCommentCreateRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FunctionsDecompilationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public FunctionsDecompilationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public FunctionsDecompilationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for checkFunctionDecompilationTask
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkFunctionDecompilationTaskCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}/decompilation/status"
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call checkFunctionDecompilationTaskValidateBeforeCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling checkFunctionDecompilationTask(Async)");
        }

        return checkFunctionDecompilationTaskCall(functionId, authorization, _callback);

    }

    /**
     * Check the status of a function decompilation
     * 
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @return BaseResponseFunctionTaskResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseFunctionTaskResponse checkFunctionDecompilationTask(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<BaseResponseFunctionTaskResponse> localVarResp = checkFunctionDecompilationTaskWithHttpInfo(functionId, authorization);
        return localVarResp.getData();
    }

    /**
     * Check the status of a function decompilation
     * 
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @return ApiResponse&lt;BaseResponseFunctionTaskResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseFunctionTaskResponse> checkFunctionDecompilationTaskWithHttpInfo(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = checkFunctionDecompilationTaskValidateBeforeCall(functionId, authorization, null);
        Type localVarReturnType = new TypeToken<BaseResponseFunctionTaskResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Check the status of a function decompilation (asynchronously)
     * 
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkFunctionDecompilationTaskAsync(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback<BaseResponseFunctionTaskResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = checkFunctionDecompilationTaskValidateBeforeCall(functionId, authorization, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseFunctionTaskResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for createDecompilationComment
     * @param functionId  (required)
     * @param functionCommentCreateRequest  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createDecompilationCommentCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nonnull FunctionCommentCreateRequest functionCommentCreateRequest, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = functionCommentCreateRequest;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}/decompilation/comments"
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createDecompilationCommentValidateBeforeCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nonnull FunctionCommentCreateRequest functionCommentCreateRequest, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling createDecompilationComment(Async)");
        }

        // verify the required parameter 'functionCommentCreateRequest' is set
        if (functionCommentCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'functionCommentCreateRequest' when calling createDecompilationComment(Async)");
        }

        return createDecompilationCommentCall(functionId, functionCommentCreateRequest, authorization, _callback);

    }

    /**
     * Create a comment for this function
     * Creates a comment associated with a specified function).
     * @param functionId  (required)
     * @param functionCommentCreateRequest  (required)
     * @param authorization API Key bearer token (optional)
     * @return BaseResponseCommentResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseCommentResponse createDecompilationComment(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nonnull FunctionCommentCreateRequest functionCommentCreateRequest, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<BaseResponseCommentResponse> localVarResp = createDecompilationCommentWithHttpInfo(functionId, functionCommentCreateRequest, authorization);
        return localVarResp.getData();
    }

    /**
     * Create a comment for this function
     * Creates a comment associated with a specified function).
     * @param functionId  (required)
     * @param functionCommentCreateRequest  (required)
     * @param authorization API Key bearer token (optional)
     * @return ApiResponse&lt;BaseResponseCommentResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseCommentResponse> createDecompilationCommentWithHttpInfo(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nonnull FunctionCommentCreateRequest functionCommentCreateRequest, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = createDecompilationCommentValidateBeforeCall(functionId, functionCommentCreateRequest, authorization, null);
        Type localVarReturnType = new TypeToken<BaseResponseCommentResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a comment for this function (asynchronously)
     * Creates a comment associated with a specified function).
     * @param functionId  (required)
     * @param functionCommentCreateRequest  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createDecompilationCommentAsync(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nonnull FunctionCommentCreateRequest functionCommentCreateRequest, @javax.annotation.Nullable String authorization, final ApiCallback<BaseResponseCommentResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createDecompilationCommentValidateBeforeCall(functionId, functionCommentCreateRequest, authorization, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseCommentResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for createFunctionDecompilationTask
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Security checks already extracted or queued </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createFunctionDecompilationTaskCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}/decompilation"
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createFunctionDecompilationTaskValidateBeforeCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling createFunctionDecompilationTask(Async)");
        }

        return createFunctionDecompilationTaskCall(functionId, authorization, _callback);

    }

    /**
     * Queues a function decompilation
     * 
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @return BaseResponseStr
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Security checks already extracted or queued </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseStr createFunctionDecompilationTask(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<BaseResponseStr> localVarResp = createFunctionDecompilationTaskWithHttpInfo(functionId, authorization);
        return localVarResp.getData();
    }

    /**
     * Queues a function decompilation
     * 
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @return ApiResponse&lt;BaseResponseStr&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Security checks already extracted or queued </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseStr> createFunctionDecompilationTaskWithHttpInfo(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = createFunctionDecompilationTaskValidateBeforeCall(functionId, authorization, null);
        Type localVarReturnType = new TypeToken<BaseResponseStr>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Queues a function decompilation (asynchronously)
     * 
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Security checks already extracted or queued </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createFunctionDecompilationTaskAsync(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback<BaseResponseStr> _callback) throws ApiException {

        okhttp3.Call localVarCall = createFunctionDecompilationTaskValidateBeforeCall(functionId, authorization, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseStr>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteDecompilationComment
     * @param commentId  (required)
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> You can only delete your own comments </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteDecompilationCommentCall(@javax.annotation.Nonnull Integer commentId, @javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}/decompilation/comments/{comment_id}"
            .replace("{" + "comment_id" + "}", localVarApiClient.escapeString(commentId.toString()))
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteDecompilationCommentValidateBeforeCall(@javax.annotation.Nonnull Integer commentId, @javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'commentId' is set
        if (commentId == null) {
            throw new ApiException("Missing the required parameter 'commentId' when calling deleteDecompilationComment(Async)");
        }

        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling deleteDecompilationComment(Async)");
        }

        return deleteDecompilationCommentCall(commentId, functionId, authorization, _callback);

    }

    /**
     * Delete a comment
     * Deletes an existing comment. Users can only delete their own comments.
     * @param commentId  (required)
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @return BaseResponseBool
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> You can only delete your own comments </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseBool deleteDecompilationComment(@javax.annotation.Nonnull Integer commentId, @javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<BaseResponseBool> localVarResp = deleteDecompilationCommentWithHttpInfo(commentId, functionId, authorization);
        return localVarResp.getData();
    }

    /**
     * Delete a comment
     * Deletes an existing comment. Users can only delete their own comments.
     * @param commentId  (required)
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @return ApiResponse&lt;BaseResponseBool&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> You can only delete your own comments </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseBool> deleteDecompilationCommentWithHttpInfo(@javax.annotation.Nonnull Integer commentId, @javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = deleteDecompilationCommentValidateBeforeCall(commentId, functionId, authorization, null);
        Type localVarReturnType = new TypeToken<BaseResponseBool>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete a comment (asynchronously)
     * Deletes an existing comment. Users can only delete their own comments.
     * @param commentId  (required)
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> You can only delete your own comments </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteDecompilationCommentAsync(@javax.annotation.Nonnull Integer commentId, @javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback<BaseResponseBool> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteDecompilationCommentValidateBeforeCall(commentId, functionId, authorization, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseBool>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getDecompilationComments
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDecompilationCommentsCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}/decompilation/comments"
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getDecompilationCommentsValidateBeforeCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling getDecompilationComments(Async)");
        }

        return getDecompilationCommentsCall(functionId, authorization, _callback);

    }

    /**
     * Get comments for this function
     * Retrieves all comments created for a specific function. Only returns comments for resources the requesting user has access to.
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @return BaseResponseListCommentResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseListCommentResponse getDecompilationComments(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<BaseResponseListCommentResponse> localVarResp = getDecompilationCommentsWithHttpInfo(functionId, authorization);
        return localVarResp.getData();
    }

    /**
     * Get comments for this function
     * Retrieves all comments created for a specific function. Only returns comments for resources the requesting user has access to.
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @return ApiResponse&lt;BaseResponseListCommentResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseListCommentResponse> getDecompilationCommentsWithHttpInfo(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = getDecompilationCommentsValidateBeforeCall(functionId, authorization, null);
        Type localVarReturnType = new TypeToken<BaseResponseListCommentResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get comments for this function (asynchronously)
     * Retrieves all comments created for a specific function. Only returns comments for resources the requesting user has access to.
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getDecompilationCommentsAsync(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback<BaseResponseListCommentResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getDecompilationCommentsValidateBeforeCall(functionId, authorization, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseListCommentResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getFunctionDecompilation
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Unable to find a decompilation for the function_id given </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionDecompilationCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}/decompilation"
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getFunctionDecompilationValidateBeforeCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling getFunctionDecompilation(Async)");
        }

        return getFunctionDecompilationCall(functionId, authorization, _callback);

    }

    /**
     * Get decompilation result
     * 
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @return BaseResponseDecompilationResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Unable to find a decompilation for the function_id given </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseDecompilationResponse getFunctionDecompilation(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<BaseResponseDecompilationResponse> localVarResp = getFunctionDecompilationWithHttpInfo(functionId, authorization);
        return localVarResp.getData();
    }

    /**
     * Get decompilation result
     * 
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @return ApiResponse&lt;BaseResponseDecompilationResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Unable to find a decompilation for the function_id given </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseDecompilationResponse> getFunctionDecompilationWithHttpInfo(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = getFunctionDecompilationValidateBeforeCall(functionId, authorization, null);
        Type localVarReturnType = new TypeToken<BaseResponseDecompilationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get decompilation result (asynchronously)
     * 
     * @param functionId  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Unable to find a decompilation for the function_id given </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionDecompilationAsync(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable String authorization, final ApiCallback<BaseResponseDecompilationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getFunctionDecompilationValidateBeforeCall(functionId, authorization, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseDecompilationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateDecompilationComment
     * @param commentId  (required)
     * @param functionId  (required)
     * @param commentUpdateRequest  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> You can only update your own comments </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateDecompilationCommentCall(@javax.annotation.Nonnull Integer commentId, @javax.annotation.Nonnull Integer functionId, @javax.annotation.Nonnull CommentUpdateRequest commentUpdateRequest, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = commentUpdateRequest;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}/decompilation/comments/{comment_id}"
            .replace("{" + "comment_id" + "}", localVarApiClient.escapeString(commentId.toString()))
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateDecompilationCommentValidateBeforeCall(@javax.annotation.Nonnull Integer commentId, @javax.annotation.Nonnull Integer functionId, @javax.annotation.Nonnull CommentUpdateRequest commentUpdateRequest, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'commentId' is set
        if (commentId == null) {
            throw new ApiException("Missing the required parameter 'commentId' when calling updateDecompilationComment(Async)");
        }

        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling updateDecompilationComment(Async)");
        }

        // verify the required parameter 'commentUpdateRequest' is set
        if (commentUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'commentUpdateRequest' when calling updateDecompilationComment(Async)");
        }

        return updateDecompilationCommentCall(commentId, functionId, commentUpdateRequest, authorization, _callback);

    }

    /**
     * Update a comment
     * Updates the content of an existing comment. Users can only update their own comments.
     * @param commentId  (required)
     * @param functionId  (required)
     * @param commentUpdateRequest  (required)
     * @param authorization API Key bearer token (optional)
     * @return BaseResponseCommentResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> You can only update your own comments </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseCommentResponse updateDecompilationComment(@javax.annotation.Nonnull Integer commentId, @javax.annotation.Nonnull Integer functionId, @javax.annotation.Nonnull CommentUpdateRequest commentUpdateRequest, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<BaseResponseCommentResponse> localVarResp = updateDecompilationCommentWithHttpInfo(commentId, functionId, commentUpdateRequest, authorization);
        return localVarResp.getData();
    }

    /**
     * Update a comment
     * Updates the content of an existing comment. Users can only update their own comments.
     * @param commentId  (required)
     * @param functionId  (required)
     * @param commentUpdateRequest  (required)
     * @param authorization API Key bearer token (optional)
     * @return ApiResponse&lt;BaseResponseCommentResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> You can only update your own comments </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseCommentResponse> updateDecompilationCommentWithHttpInfo(@javax.annotation.Nonnull Integer commentId, @javax.annotation.Nonnull Integer functionId, @javax.annotation.Nonnull CommentUpdateRequest commentUpdateRequest, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = updateDecompilationCommentValidateBeforeCall(commentId, functionId, commentUpdateRequest, authorization, null);
        Type localVarReturnType = new TypeToken<BaseResponseCommentResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a comment (asynchronously)
     * Updates the content of an existing comment. Users can only update their own comments.
     * @param commentId  (required)
     * @param functionId  (required)
     * @param commentUpdateRequest  (required)
     * @param authorization API Key bearer token (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> You can only update your own comments </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateDecompilationCommentAsync(@javax.annotation.Nonnull Integer commentId, @javax.annotation.Nonnull Integer functionId, @javax.annotation.Nonnull CommentUpdateRequest commentUpdateRequest, @javax.annotation.Nullable String authorization, final ApiCallback<BaseResponseCommentResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateDecompilationCommentValidateBeforeCall(commentId, functionId, commentUpdateRequest, authorization, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseCommentResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
