/*
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.reveng.api;

import ai.reveng.invoker.ApiCallback;
import ai.reveng.invoker.ApiClient;
import ai.reveng.invoker.ApiException;
import ai.reveng.invoker.ApiResponse;
import ai.reveng.invoker.Configuration;
import ai.reveng.invoker.Pair;
import ai.reveng.invoker.ProgressRequestBody;
import ai.reveng.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.reveng.model.AiUnstripRequest;
import ai.reveng.model.AnalysisFunctionMatchingRequest;
import ai.reveng.model.AutoUnstripRequest;
import ai.reveng.model.AutoUnstripResponse;
import ai.reveng.model.BaseResponse;
import ai.reveng.model.BaseResponseAnalysisStringsResponse;
import ai.reveng.model.BaseResponseCalleesCallerFunctionsResponse;
import ai.reveng.model.BaseResponseFunctionBlocksResponse;
import ai.reveng.model.BaseResponseFunctionCapabilityResponse;
import ai.reveng.model.BaseResponseFunctionStringsResponse;
import ai.reveng.model.BaseResponseFunctionsDetailResponse;
import ai.reveng.model.FunctionMatchingBatchResponse;
import ai.reveng.model.FunctionMatchingRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FunctionsCoreApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public FunctionsCoreApi() {
        this(Configuration.getDefaultApiClient());
    }

    public FunctionsCoreApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for aiUnstrip
     * @param analysisId  (required)
     * @param aiUnstripRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call aiUnstripCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AiUnstripRequest aiUnstripRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = aiUnstripRequest;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/functions/ai-unstrip"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call aiUnstripValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AiUnstripRequest aiUnstripRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling aiUnstrip(Async)");
        }

        // verify the required parameter 'aiUnstripRequest' is set
        if (aiUnstripRequest == null) {
            throw new ApiException("Missing the required parameter 'aiUnstripRequest' when calling aiUnstrip(Async)");
        }

        return aiUnstripCall(analysisId, aiUnstripRequest, _callback);

    }

    /**
     * Performs matching and auto-unstrip for an analysis and its functions
     * Takes in the analysis ID, uses the functions ID&#39;s from it and settings to find the nearest function groups for each function that&#39;s within the system
     * @param analysisId  (required)
     * @param aiUnstripRequest  (required)
     * @return AutoUnstripResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public AutoUnstripResponse aiUnstrip(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AiUnstripRequest aiUnstripRequest) throws ApiException {
        ApiResponse<AutoUnstripResponse> localVarResp = aiUnstripWithHttpInfo(analysisId, aiUnstripRequest);
        return localVarResp.getData();
    }

    /**
     * Performs matching and auto-unstrip for an analysis and its functions
     * Takes in the analysis ID, uses the functions ID&#39;s from it and settings to find the nearest function groups for each function that&#39;s within the system
     * @param analysisId  (required)
     * @param aiUnstripRequest  (required)
     * @return ApiResponse&lt;AutoUnstripResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AutoUnstripResponse> aiUnstripWithHttpInfo(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AiUnstripRequest aiUnstripRequest) throws ApiException {
        okhttp3.Call localVarCall = aiUnstripValidateBeforeCall(analysisId, aiUnstripRequest, null);
        Type localVarReturnType = new TypeToken<AutoUnstripResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Performs matching and auto-unstrip for an analysis and its functions (asynchronously)
     * Takes in the analysis ID, uses the functions ID&#39;s from it and settings to find the nearest function groups for each function that&#39;s within the system
     * @param analysisId  (required)
     * @param aiUnstripRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call aiUnstripAsync(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AiUnstripRequest aiUnstripRequest, final ApiCallback<AutoUnstripResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = aiUnstripValidateBeforeCall(analysisId, aiUnstripRequest, _callback);
        Type localVarReturnType = new TypeToken<AutoUnstripResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for analysisFunctionMatching
     * @param analysisId  (required)
     * @param analysisFunctionMatchingRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call analysisFunctionMatchingCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AnalysisFunctionMatchingRequest analysisFunctionMatchingRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = analysisFunctionMatchingRequest;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/functions/matches"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call analysisFunctionMatchingValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AnalysisFunctionMatchingRequest analysisFunctionMatchingRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling analysisFunctionMatching(Async)");
        }

        // verify the required parameter 'analysisFunctionMatchingRequest' is set
        if (analysisFunctionMatchingRequest == null) {
            throw new ApiException("Missing the required parameter 'analysisFunctionMatchingRequest' when calling analysisFunctionMatching(Async)");
        }

        return analysisFunctionMatchingCall(analysisId, analysisFunctionMatchingRequest, _callback);

    }

    /**
     * Perform matching for the functions of an analysis
     * Takes in an analysis id and settings and matches the nearest functions to the ones associated with it. Results can optionally be filtered by collection, binary, debug type or (other) function ids
     * @param analysisId  (required)
     * @param analysisFunctionMatchingRequest  (required)
     * @return FunctionMatchingBatchResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public FunctionMatchingBatchResponse analysisFunctionMatching(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AnalysisFunctionMatchingRequest analysisFunctionMatchingRequest) throws ApiException {
        ApiResponse<FunctionMatchingBatchResponse> localVarResp = analysisFunctionMatchingWithHttpInfo(analysisId, analysisFunctionMatchingRequest);
        return localVarResp.getData();
    }

    /**
     * Perform matching for the functions of an analysis
     * Takes in an analysis id and settings and matches the nearest functions to the ones associated with it. Results can optionally be filtered by collection, binary, debug type or (other) function ids
     * @param analysisId  (required)
     * @param analysisFunctionMatchingRequest  (required)
     * @return ApiResponse&lt;FunctionMatchingBatchResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FunctionMatchingBatchResponse> analysisFunctionMatchingWithHttpInfo(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AnalysisFunctionMatchingRequest analysisFunctionMatchingRequest) throws ApiException {
        okhttp3.Call localVarCall = analysisFunctionMatchingValidateBeforeCall(analysisId, analysisFunctionMatchingRequest, null);
        Type localVarReturnType = new TypeToken<FunctionMatchingBatchResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Perform matching for the functions of an analysis (asynchronously)
     * Takes in an analysis id and settings and matches the nearest functions to the ones associated with it. Results can optionally be filtered by collection, binary, debug type or (other) function ids
     * @param analysisId  (required)
     * @param analysisFunctionMatchingRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call analysisFunctionMatchingAsync(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AnalysisFunctionMatchingRequest analysisFunctionMatchingRequest, final ApiCallback<FunctionMatchingBatchResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = analysisFunctionMatchingValidateBeforeCall(analysisId, analysisFunctionMatchingRequest, _callback);
        Type localVarReturnType = new TypeToken<FunctionMatchingBatchResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for autoUnstrip
     * @param analysisId  (required)
     * @param autoUnstripRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call autoUnstripCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AutoUnstripRequest autoUnstripRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = autoUnstripRequest;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/functions/auto-unstrip"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call autoUnstripValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AutoUnstripRequest autoUnstripRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling autoUnstrip(Async)");
        }

        // verify the required parameter 'autoUnstripRequest' is set
        if (autoUnstripRequest == null) {
            throw new ApiException("Missing the required parameter 'autoUnstripRequest' when calling autoUnstrip(Async)");
        }

        return autoUnstripCall(analysisId, autoUnstripRequest, _callback);

    }

    /**
     * Performs matching and auto-unstrip for an analysis and its functions
     * Takes in the analysis ID, uses the functions ID&#39;s from it and settings to find the nearest function for each function that&#39;s within the system
     * @param analysisId  (required)
     * @param autoUnstripRequest  (required)
     * @return AutoUnstripResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public AutoUnstripResponse autoUnstrip(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AutoUnstripRequest autoUnstripRequest) throws ApiException {
        ApiResponse<AutoUnstripResponse> localVarResp = autoUnstripWithHttpInfo(analysisId, autoUnstripRequest);
        return localVarResp.getData();
    }

    /**
     * Performs matching and auto-unstrip for an analysis and its functions
     * Takes in the analysis ID, uses the functions ID&#39;s from it and settings to find the nearest function for each function that&#39;s within the system
     * @param analysisId  (required)
     * @param autoUnstripRequest  (required)
     * @return ApiResponse&lt;AutoUnstripResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AutoUnstripResponse> autoUnstripWithHttpInfo(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AutoUnstripRequest autoUnstripRequest) throws ApiException {
        okhttp3.Call localVarCall = autoUnstripValidateBeforeCall(analysisId, autoUnstripRequest, null);
        Type localVarReturnType = new TypeToken<AutoUnstripResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Performs matching and auto-unstrip for an analysis and its functions (asynchronously)
     * Takes in the analysis ID, uses the functions ID&#39;s from it and settings to find the nearest function for each function that&#39;s within the system
     * @param analysisId  (required)
     * @param autoUnstripRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call autoUnstripAsync(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nonnull AutoUnstripRequest autoUnstripRequest, final ApiCallback<AutoUnstripResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = autoUnstripValidateBeforeCall(analysisId, autoUnstripRequest, _callback);
        Type localVarReturnType = new TypeToken<AutoUnstripResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for batchFunctionMatching
     * @param functionMatchingRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call batchFunctionMatchingCall(@javax.annotation.Nonnull FunctionMatchingRequest functionMatchingRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = functionMatchingRequest;

        // create path and map variables
        String localVarPath = "/v2/functions/matches";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call batchFunctionMatchingValidateBeforeCall(@javax.annotation.Nonnull FunctionMatchingRequest functionMatchingRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'functionMatchingRequest' is set
        if (functionMatchingRequest == null) {
            throw new ApiException("Missing the required parameter 'functionMatchingRequest' when calling batchFunctionMatching(Async)");
        }

        return batchFunctionMatchingCall(functionMatchingRequest, _callback);

    }

    /**
     * Perform function matching for an arbitrary batch of functions, binaries or collections
     * Takes in an input of functions ID&#39;s and settings and finds the nearest functions for each function that&#39;s within the system
     * @param functionMatchingRequest  (required)
     * @return FunctionMatchingBatchResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public FunctionMatchingBatchResponse batchFunctionMatching(@javax.annotation.Nonnull FunctionMatchingRequest functionMatchingRequest) throws ApiException {
        ApiResponse<FunctionMatchingBatchResponse> localVarResp = batchFunctionMatchingWithHttpInfo(functionMatchingRequest);
        return localVarResp.getData();
    }

    /**
     * Perform function matching for an arbitrary batch of functions, binaries or collections
     * Takes in an input of functions ID&#39;s and settings and finds the nearest functions for each function that&#39;s within the system
     * @param functionMatchingRequest  (required)
     * @return ApiResponse&lt;FunctionMatchingBatchResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<FunctionMatchingBatchResponse> batchFunctionMatchingWithHttpInfo(@javax.annotation.Nonnull FunctionMatchingRequest functionMatchingRequest) throws ApiException {
        okhttp3.Call localVarCall = batchFunctionMatchingValidateBeforeCall(functionMatchingRequest, null);
        Type localVarReturnType = new TypeToken<FunctionMatchingBatchResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Perform function matching for an arbitrary batch of functions, binaries or collections (asynchronously)
     * Takes in an input of functions ID&#39;s and settings and finds the nearest functions for each function that&#39;s within the system
     * @param functionMatchingRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call batchFunctionMatchingAsync(@javax.annotation.Nonnull FunctionMatchingRequest functionMatchingRequest, final ApiCallback<FunctionMatchingBatchResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = batchFunctionMatchingValidateBeforeCall(functionMatchingRequest, _callback);
        Type localVarReturnType = new TypeToken<FunctionMatchingBatchResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for cancelAiUnstrip
     * @param analysisId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call cancelAiUnstripCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/functions/ai-unstrip/cancel"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call cancelAiUnstripValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling cancelAiUnstrip(Async)");
        }

        return cancelAiUnstripCall(analysisId, _callback);

    }

    /**
     * Cancels a running ai-unstrip
     * Takes in the analysis ID and cancels a running ai-unstrip operation
     * @param analysisId  (required)
     * @return AutoUnstripResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public AutoUnstripResponse cancelAiUnstrip(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        ApiResponse<AutoUnstripResponse> localVarResp = cancelAiUnstripWithHttpInfo(analysisId);
        return localVarResp.getData();
    }

    /**
     * Cancels a running ai-unstrip
     * Takes in the analysis ID and cancels a running ai-unstrip operation
     * @param analysisId  (required)
     * @return ApiResponse&lt;AutoUnstripResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AutoUnstripResponse> cancelAiUnstripWithHttpInfo(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        okhttp3.Call localVarCall = cancelAiUnstripValidateBeforeCall(analysisId, null);
        Type localVarReturnType = new TypeToken<AutoUnstripResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Cancels a running ai-unstrip (asynchronously)
     * Takes in the analysis ID and cancels a running ai-unstrip operation
     * @param analysisId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call cancelAiUnstripAsync(@javax.annotation.Nonnull Integer analysisId, final ApiCallback<AutoUnstripResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = cancelAiUnstripValidateBeforeCall(analysisId, _callback);
        Type localVarReturnType = new TypeToken<AutoUnstripResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for cancelAutoUnstrip
     * @param analysisId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call cancelAutoUnstripCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/functions/unstrip/cancel"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call cancelAutoUnstripValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling cancelAutoUnstrip(Async)");
        }

        return cancelAutoUnstripCall(analysisId, _callback);

    }

    /**
     * Cancels a running auto-unstrip
     * Takes in the analysis ID and cancels a running auto-unstrip operation
     * @param analysisId  (required)
     * @return AutoUnstripResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public AutoUnstripResponse cancelAutoUnstrip(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        ApiResponse<AutoUnstripResponse> localVarResp = cancelAutoUnstripWithHttpInfo(analysisId);
        return localVarResp.getData();
    }

    /**
     * Cancels a running auto-unstrip
     * Takes in the analysis ID and cancels a running auto-unstrip operation
     * @param analysisId  (required)
     * @return ApiResponse&lt;AutoUnstripResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AutoUnstripResponse> cancelAutoUnstripWithHttpInfo(@javax.annotation.Nonnull Integer analysisId) throws ApiException {
        okhttp3.Call localVarCall = cancelAutoUnstripValidateBeforeCall(analysisId, null);
        Type localVarReturnType = new TypeToken<AutoUnstripResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Cancels a running auto-unstrip (asynchronously)
     * Takes in the analysis ID and cancels a running auto-unstrip operation
     * @param analysisId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call cancelAutoUnstripAsync(@javax.annotation.Nonnull Integer analysisId, final ApiCallback<AutoUnstripResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = cancelAutoUnstripValidateBeforeCall(analysisId, _callback);
        Type localVarReturnType = new TypeToken<AutoUnstripResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAnalysisStrings
     * @param analysisId  (required)
     * @param page The page number to retrieve. (optional, default to 1)
     * @param pageSize Number of items per page. (optional, default to 100)
     * @param search Search is applied to string value (optional)
     * @param functionSearch Search is applied to function names (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAnalysisStringsCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String search, @javax.annotation.Nullable String functionSearch, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/analyses/{analysis_id}/functions/strings"
            .replace("{" + "analysis_id" + "}", localVarApiClient.escapeString(analysisId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        if (search != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("search", search));
        }

        if (functionSearch != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("function_search", functionSearch));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAnalysisStringsValidateBeforeCall(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String search, @javax.annotation.Nullable String functionSearch, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'analysisId' is set
        if (analysisId == null) {
            throw new ApiException("Missing the required parameter 'analysisId' when calling getAnalysisStrings(Async)");
        }

        return getAnalysisStringsCall(analysisId, page, pageSize, search, functionSearch, _callback);

    }

    /**
     * Get string information found in the Analysis
     * Get string information found in the analysis
     * @param analysisId  (required)
     * @param page The page number to retrieve. (optional, default to 1)
     * @param pageSize Number of items per page. (optional, default to 100)
     * @param search Search is applied to string value (optional)
     * @param functionSearch Search is applied to function names (optional)
     * @return BaseResponseAnalysisStringsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseAnalysisStringsResponse getAnalysisStrings(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String search, @javax.annotation.Nullable String functionSearch) throws ApiException {
        ApiResponse<BaseResponseAnalysisStringsResponse> localVarResp = getAnalysisStringsWithHttpInfo(analysisId, page, pageSize, search, functionSearch);
        return localVarResp.getData();
    }

    /**
     * Get string information found in the Analysis
     * Get string information found in the analysis
     * @param analysisId  (required)
     * @param page The page number to retrieve. (optional, default to 1)
     * @param pageSize Number of items per page. (optional, default to 100)
     * @param search Search is applied to string value (optional)
     * @param functionSearch Search is applied to function names (optional)
     * @return ApiResponse&lt;BaseResponseAnalysisStringsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseAnalysisStringsResponse> getAnalysisStringsWithHttpInfo(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String search, @javax.annotation.Nullable String functionSearch) throws ApiException {
        okhttp3.Call localVarCall = getAnalysisStringsValidateBeforeCall(analysisId, page, pageSize, search, functionSearch, null);
        Type localVarReturnType = new TypeToken<BaseResponseAnalysisStringsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get string information found in the Analysis (asynchronously)
     * Get string information found in the analysis
     * @param analysisId  (required)
     * @param page The page number to retrieve. (optional, default to 1)
     * @param pageSize Number of items per page. (optional, default to 100)
     * @param search Search is applied to string value (optional)
     * @param functionSearch Search is applied to function names (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAnalysisStringsAsync(@javax.annotation.Nonnull Integer analysisId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String search, @javax.annotation.Nullable String functionSearch, final ApiCallback<BaseResponseAnalysisStringsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAnalysisStringsValidateBeforeCall(analysisId, page, pageSize, search, functionSearch, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseAnalysisStringsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getFunctionBlocks
     * @param functionId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionBlocksCall(@javax.annotation.Nonnull Integer functionId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}/blocks"
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getFunctionBlocksValidateBeforeCall(@javax.annotation.Nonnull Integer functionId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling getFunctionBlocks(Async)");
        }

        return getFunctionBlocksCall(functionId, _callback);

    }

    /**
     * Get disassembly blocks related to the function
     * Get disassembly blocks related to the function
     * @param functionId  (required)
     * @return BaseResponseFunctionBlocksResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseFunctionBlocksResponse getFunctionBlocks(@javax.annotation.Nonnull Integer functionId) throws ApiException {
        ApiResponse<BaseResponseFunctionBlocksResponse> localVarResp = getFunctionBlocksWithHttpInfo(functionId);
        return localVarResp.getData();
    }

    /**
     * Get disassembly blocks related to the function
     * Get disassembly blocks related to the function
     * @param functionId  (required)
     * @return ApiResponse&lt;BaseResponseFunctionBlocksResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseFunctionBlocksResponse> getFunctionBlocksWithHttpInfo(@javax.annotation.Nonnull Integer functionId) throws ApiException {
        okhttp3.Call localVarCall = getFunctionBlocksValidateBeforeCall(functionId, null);
        Type localVarReturnType = new TypeToken<BaseResponseFunctionBlocksResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get disassembly blocks related to the function (asynchronously)
     * Get disassembly blocks related to the function
     * @param functionId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionBlocksAsync(@javax.annotation.Nonnull Integer functionId, final ApiCallback<BaseResponseFunctionBlocksResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getFunctionBlocksValidateBeforeCall(functionId, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseFunctionBlocksResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getFunctionCalleesCallers
     * @param functionId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionCalleesCallersCall(@javax.annotation.Nonnull Integer functionId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}/callees_callers"
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getFunctionCalleesCallersValidateBeforeCall(@javax.annotation.Nonnull Integer functionId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling getFunctionCalleesCallers(Async)");
        }

        return getFunctionCalleesCallersCall(functionId, _callback);

    }

    /**
     * Get list of functions that call or are called by the specified function
     * 
     * @param functionId  (required)
     * @return BaseResponseCalleesCallerFunctionsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseCalleesCallerFunctionsResponse getFunctionCalleesCallers(@javax.annotation.Nonnull Integer functionId) throws ApiException {
        ApiResponse<BaseResponseCalleesCallerFunctionsResponse> localVarResp = getFunctionCalleesCallersWithHttpInfo(functionId);
        return localVarResp.getData();
    }

    /**
     * Get list of functions that call or are called by the specified function
     * 
     * @param functionId  (required)
     * @return ApiResponse&lt;BaseResponseCalleesCallerFunctionsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseCalleesCallerFunctionsResponse> getFunctionCalleesCallersWithHttpInfo(@javax.annotation.Nonnull Integer functionId) throws ApiException {
        okhttp3.Call localVarCall = getFunctionCalleesCallersValidateBeforeCall(functionId, null);
        Type localVarReturnType = new TypeToken<BaseResponseCalleesCallerFunctionsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get list of functions that call or are called by the specified function (asynchronously)
     * 
     * @param functionId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionCalleesCallersAsync(@javax.annotation.Nonnull Integer functionId, final ApiCallback<BaseResponseCalleesCallerFunctionsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getFunctionCalleesCallersValidateBeforeCall(functionId, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseCalleesCallerFunctionsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getFunctionCapabilities
     * @param functionId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionCapabilitiesCall(@javax.annotation.Nonnull Integer functionId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}/capabilities"
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getFunctionCapabilitiesValidateBeforeCall(@javax.annotation.Nonnull Integer functionId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling getFunctionCapabilities(Async)");
        }

        return getFunctionCapabilitiesCall(functionId, _callback);

    }

    /**
     * Retrieve a functions capabilities
     * 
     * @param functionId  (required)
     * @return BaseResponseFunctionCapabilityResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseFunctionCapabilityResponse getFunctionCapabilities(@javax.annotation.Nonnull Integer functionId) throws ApiException {
        ApiResponse<BaseResponseFunctionCapabilityResponse> localVarResp = getFunctionCapabilitiesWithHttpInfo(functionId);
        return localVarResp.getData();
    }

    /**
     * Retrieve a functions capabilities
     * 
     * @param functionId  (required)
     * @return ApiResponse&lt;BaseResponseFunctionCapabilityResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseFunctionCapabilityResponse> getFunctionCapabilitiesWithHttpInfo(@javax.annotation.Nonnull Integer functionId) throws ApiException {
        okhttp3.Call localVarCall = getFunctionCapabilitiesValidateBeforeCall(functionId, null);
        Type localVarReturnType = new TypeToken<BaseResponseFunctionCapabilityResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve a functions capabilities (asynchronously)
     * 
     * @param functionId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionCapabilitiesAsync(@javax.annotation.Nonnull Integer functionId, final ApiCallback<BaseResponseFunctionCapabilityResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getFunctionCapabilitiesValidateBeforeCall(functionId, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseFunctionCapabilityResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getFunctionDetails
     * @param functionId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionDetailsCall(@javax.annotation.Nonnull Integer functionId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}"
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getFunctionDetailsValidateBeforeCall(@javax.annotation.Nonnull Integer functionId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling getFunctionDetails(Async)");
        }

        return getFunctionDetailsCall(functionId, _callback);

    }

    /**
     * Get function details
     * 
     * @param functionId  (required)
     * @return BaseResponseFunctionsDetailResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseFunctionsDetailResponse getFunctionDetails(@javax.annotation.Nonnull Integer functionId) throws ApiException {
        ApiResponse<BaseResponseFunctionsDetailResponse> localVarResp = getFunctionDetailsWithHttpInfo(functionId);
        return localVarResp.getData();
    }

    /**
     * Get function details
     * 
     * @param functionId  (required)
     * @return ApiResponse&lt;BaseResponseFunctionsDetailResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseFunctionsDetailResponse> getFunctionDetailsWithHttpInfo(@javax.annotation.Nonnull Integer functionId) throws ApiException {
        okhttp3.Call localVarCall = getFunctionDetailsValidateBeforeCall(functionId, null);
        Type localVarReturnType = new TypeToken<BaseResponseFunctionsDetailResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get function details (asynchronously)
     * 
     * @param functionId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionDetailsAsync(@javax.annotation.Nonnull Integer functionId, final ApiCallback<BaseResponseFunctionsDetailResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getFunctionDetailsValidateBeforeCall(functionId, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseFunctionsDetailResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getFunctionStrings
     * @param functionId  (required)
     * @param page The page number to retrieve. (optional, default to 1)
     * @param pageSize Number of items per page. (optional, default to 100)
     * @param search Search is applied to string value (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionStringsCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String search, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/functions/{function_id}/strings"
            .replace("{" + "function_id" + "}", localVarApiClient.escapeString(functionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_size", pageSize));
        }

        if (search != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("search", search));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getFunctionStringsValidateBeforeCall(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String search, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'functionId' is set
        if (functionId == null) {
            throw new ApiException("Missing the required parameter 'functionId' when calling getFunctionStrings(Async)");
        }

        return getFunctionStringsCall(functionId, page, pageSize, search, _callback);

    }

    /**
     * Get string information found in the function
     * Get string information found in the function
     * @param functionId  (required)
     * @param page The page number to retrieve. (optional, default to 1)
     * @param pageSize Number of items per page. (optional, default to 100)
     * @param search Search is applied to string value (optional)
     * @return BaseResponseFunctionStringsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public BaseResponseFunctionStringsResponse getFunctionStrings(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String search) throws ApiException {
        ApiResponse<BaseResponseFunctionStringsResponse> localVarResp = getFunctionStringsWithHttpInfo(functionId, page, pageSize, search);
        return localVarResp.getData();
    }

    /**
     * Get string information found in the function
     * Get string information found in the function
     * @param functionId  (required)
     * @param page The page number to retrieve. (optional, default to 1)
     * @param pageSize Number of items per page. (optional, default to 100)
     * @param search Search is applied to string value (optional)
     * @return ApiResponse&lt;BaseResponseFunctionStringsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BaseResponseFunctionStringsResponse> getFunctionStringsWithHttpInfo(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String search) throws ApiException {
        okhttp3.Call localVarCall = getFunctionStringsValidateBeforeCall(functionId, page, pageSize, search, null);
        Type localVarReturnType = new TypeToken<BaseResponseFunctionStringsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get string information found in the function (asynchronously)
     * Get string information found in the function
     * @param functionId  (required)
     * @param page The page number to retrieve. (optional, default to 1)
     * @param pageSize Number of items per page. (optional, default to 100)
     * @param search Search is applied to string value (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Invalid request parameters </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getFunctionStringsAsync(@javax.annotation.Nonnull Integer functionId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer pageSize, @javax.annotation.Nullable String search, final ApiCallback<BaseResponseFunctionStringsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getFunctionStringsValidateBeforeCall(functionId, page, pageSize, search, _callback);
        Type localVarReturnType = new TypeToken<BaseResponseFunctionStringsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
